export const LOCALES = [
  { code: 'en', name: 'English' },
  { code: 'lt', name: 'Lietuvių' },
  { code: 'es', name: 'Español' },
  { code: 'de', name: 'Deutsch' },
  { code: 'uk', name: 'Українська' },
];

const en = {
  'intro.eyebrow':'A calmer kind of puzzle','intro.title':'Think clearly.<br><em>Play beautifully.</em>','intro.lead':'A premium Sudoku ritual with thoughtful hints, daily challenges and progress that stays on your device.','intro.featureOffline':'Truly offline','intro.featureOfflineText':'Play anywhere after your first visit.','intro.featureCoach':'Gentle coaching','intro.featureCoachText':'Visible hints help you find the next step.','intro.featureProgress':'Personal progress','intro.featureProgressText':'Build streaks and unlock achievements.','intro.start':'Begin your first puzzle','intro.note':'Your language and preferences are saved permanently on this device.','intro.daily':'Daily challenge','intro.ready':'Ready when you are',
  'dedication.label':'A personal dedication','dedication.madeFor':'Made especially for Edmundas','dedication.message':'A quiet place for logic, focus, and beautiful thinking—created with care.','dedication.footer':'Made for Edmundas, for moments of focus.',
  'settings.personalize':'Make it yours','settings.title':'Settings','settings.language':'Language','settings.languageHelp':'Saved permanently on this device','settings.haptics':'Haptic feedback','settings.hapticsHelp':'Gentle vibration on supported phones','settings.autoPause':'Automatic pause','settings.autoPauseHelp':'Pause when Sudodoku moves to the background','settings.replayIntro':'Replay introduction',
  'game.currentPuzzle':'Current puzzle','game.mistakes':'Mistakes','game.paused':'Game paused','game.resume':'Tap to find your flow','game.newGame':'New game','game.progress':'Puzzle progress','game.progressText':'{count} of 81 cells','mode.classic':'Classic','mode.daily':'Daily',
  'tools.undo':'Undo','tools.erase':'Erase','tools.notes':'Notes','tools.smartNotes':'Smart notes','tools.hint':'Hint','tools.on':'On','tools.off':'Off',
  'difficulty.easy':'Easy','difficulty.easyMood':'Relaxed','difficulty.medium':'Medium','difficulty.mediumMood':'Balanced','difficulty.hard':'Hard','difficulty.hardMood':'Focused','difficulty.expert':'Expert','difficulty.expertMood':'Fearless',
  'daily.practice':'Daily practice','daily.headline':'Find your<br><em>flow.</em>','daily.tagline':'Quiet the noise. One number at a time.','daily.quote':'Logic will get you from A to B. Imagination will take you everywhere.','daily.today':'Today’s challenge','daily.complete':'Daily complete','daily.play':'Play now','daily.replay':'Replay','daily.streak':'{count} day streak','daily.streakPlural':'{count} day streak',
  'hint.title':'Row {row}, column {column} is {value}','hint.text':'The golden cell is revealed. Scan its row, column and 3×3 box to see what this unlocks.','hint.revealed':'Hint revealed','hint.look':'Look at the highlighted cell.',
  'footer.focus':'Made for moments of focus.','footer.offline':'Offline ready',
  'result.time':'Time','result.score':'Focus score','result.unlocked':'Achievement unlocked','result.playAnother':'Play another','result.share':'Share result','result.complete':'Puzzle complete','result.dailyComplete':'Daily challenge complete','result.flawless':'Flawless focus.','result.beautiful':'Beautifully done.','result.dailyText':'Today’s grid is complete. Your daily rhythm is growing.','result.completeText':'You found your flow and finished the puzzle.','result.gameOver':'Game over','result.almost':'Almost there.','result.failedText':'Three little slips. Take a breath and begin again.',
  'stats.practice':'Your practice','stats.title':'Statistics','stats.played':'Played','stats.winRate':'Win rate','stats.streak':'Streak','stats.best':'Best time','stats.points':'Focus points','stats.daily':'Daily wins','stats.achievements':'Achievements','stats.keepPlaying':'Keep playing',
  'achievement.first-flow':'First flow','achievement.clean-grid':'Perfect solve','achievement.pure-logic':'Pure logic','achievement.speed-focus':'Under 5 min','achievement.daily-devotion':'Daily devotion','achievement.streak-three':'3 day streak','achievement.expert-mind':'Expert mind','achievement.new':'New milestone',
  'achievement.first-flow.desc':'Complete your first puzzle.','achievement.clean-grid.desc':'Finish a puzzle without a mistake.','achievement.pure-logic.desc':'Win without hints or smart notes.','achievement.speed-focus.desc':'Finish any timed puzzle in under 5 minutes.','achievement.daily-devotion.desc':'Complete your first Daily challenge.','achievement.streak-three.desc':'Reach a 3-day Daily streak.','achievement.expert-mind.desc':'Complete an Expert puzzle.',
  'achievement.explorer':'Across the map','achievement.explorer.desc':'Win once in Killer, Hyper, and Mini.','achievement.mini-sprint':'Pocket lightning','achievement.mini-sprint.desc':'Finish Mini 6×6 in under 90 seconds.','achievement.perfect-ten':'Unshaken','achievement.perfect-ten.desc':'Complete 10 perfect puzzles in a row.',
  'achievement.killer-adept':'Cage breaker','achievement.killer-adept.desc':'Complete 25 Killer puzzles.','achievement.hyper-architect':'Hyper architect','achievement.hyper-architect.desc':'Complete 25 Hyper puzzles.','achievement.zen-master':'Still water','achievement.zen-master.desc':'Complete 50 Zen puzzles.','achievement.variant-voyager':'Variant voyager','achievement.variant-voyager.desc':'Complete 100 variant puzzles.','achievement.logic-fifty':'Pure reason','achievement.logic-fifty.desc':'Win 50 puzzles without hints or smart notes.','achievement.expert-pure':'No safety net','achievement.expert-pure.desc':'Win 50 Expert puzzles without help.','achievement.weekly-ten':'Quest keeper','achievement.weekly-ten.desc':'Complete 10 Weekly quests.','achievement.daily-thirty':'Monthly ritual','achievement.daily-thirty.desc':'Reach a 30-day Daily streak.','achievement.century':'Century club','achievement.century.desc':'Complete 100 puzzles.',
  'achievement.perfect-century':'Diamond precision','achievement.perfect-century.desc':'Complete 100 puzzles without a mistake.','achievement.logic-legend':'Logic legend','achievement.logic-legend.desc':'Win 250 puzzles without help.','achievement.weekly-fifty':'Relentless explorer','achievement.weekly-fifty.desc':'Complete 50 Weekly quests.','achievement.level-twenty-five':'Focused ascent','achievement.level-twenty-five.desc':'Reach progression level 25.','achievement.deep-focus':'Deep focus','achievement.deep-focus.desc':'Spend 100 hours solving completed puzzles.','achievement.daily-century':'Hundred mornings','achievement.daily-century.desc':'Reach a 100-day Daily streak.','achievement.year-of-focus':'Year of focus','achievement.year-of-focus.desc':'Maintain a 365-day Daily streak.','achievement.grandmaster':'Sudodoku grandmaster','achievement.grandmaster.desc':'Complete 1,000 puzzles.','achievement.level-fifty':'Beyond mastery','achievement.level-fifty.desc':'Reach progression level 50.',
  'achievement.night-owl':'Moonlit mind','achievement.night-owl.desc':'Complete a puzzle between midnight and 5 a.m.','achievement.close-call':'On the edge','achievement.close-call.desc':'Win after making exactly two mistakes.','achievement.no-pencil':'Without a trace','achievement.no-pencil.desc':'Complete a Hard or Expert puzzle without hints or any notes.','achievement.patient-mind':'Patient mind','achievement.patient-mind.desc':'Solve for at least 45 minutes and finish without a hint.',
  'achievement.tier.common':'Common','achievement.tier.rare':'Rare','achievement.tier.epic':'Epic','achievement.tier.legendary':'Legendary','achievement.tier.mythic':'Mythic','achievement.tier.secret':'Secret','achievement.completed':'Completed','achievement.hours':'hours','achievement.multiple':'{count} achievements unlocked','achievement.secret':'Secret achievement','achievement.secret.desc':'Its requirement remains hidden until you unlock it.','achievement.hidden':'Hidden','achievement.history':'Achievement history','achievement.historyEmpty':'Your future milestones will appear here.','achievement.unlockedEvent':'Achievement unlocked','achievement.almostThere':'Milestone within reach','achievement.styleUnlocked':'New style unlocked','achievement.progressEvent':'{current} of {target} complete','achievement.historyCount':'{count} earned',
  'toast.restored':'Welcome back — game restored','toast.creating':'Creating a fresh puzzle…','toast.dailyReady':'Today’s challenge is ready','toast.puzzleReady':'{difficulty} puzzle ready','toast.smartNotes':'Smart notes mapped {count} candidates','toast.shared':'Result shared','toast.copied':'Result copied','toast.cardSaved':'Result card saved','toast.offlineLater':'Offline mode will be ready next time','toast.languageSaved':'Language saved permanently',
  'share.text':'Sudodoku {difficulty} · {time} · {mistakes} mistakes · {score} focus points','share.title':'My Sudodoku result',
  'common.notNow':'Not now','common.done':'Done','common.settings':'Settings','common.statistics':'Statistics','common.sound':'Sound','common.theme':'Theme','common.pause':'Pause game','common.language':'Language',
  'game.progressOf':'{count} of {total} cells','mode.classicHelp':'The timeless 9×9 game','mode.killer':'Killer','mode.killerHelp':'Cages and sums','mode.hyper':'Hyper','mode.hyperHelp':'Four extra regions','mode.mini':'Mini 6×6','mode.miniHelp':'Quick, compact focus','mode.zen':'Zen','mode.zenHelp':'No timer or mistakes',
  'unit.row':'row {number}','unit.column':'column {number}','unit.box':'box {number}','unit.hyper':'hyper region {number}',
  'technique.nakedSingle.title':'Naked single · R{row}C{column} = {value}','technique.nakedSingle.text':'Only {value} can legally fit this cell. Every other candidate is already present in its row, column or box.','technique.hiddenSingle.title':'Hidden single · {value}','technique.hiddenSingle.text':'In {unitLabel}, {value} can appear only at {cellsLabel}.','technique.nakedPair.title':'Naked pair · {pairLabel}','technique.nakedPair.text':'{cellsLabel} reserve {pairLabel} in {unitLabel}, so those candidates are removed from {targetsLabel}.','technique.xWing.title':'X-Wing · candidate {value}','technique.xWing.text':'The four corners at {cellsLabel} lock {value} across lines {linesLabel}, eliminating it from {targetsLabel}.','technique.reveal.title':'Guided reveal · R{row}C{column} = {value}','technique.reveal.text':'No supported single, pair or X-Wing is available, so this cell is revealed to keep your solve moving.',
  'quest.weekly':'Weekly quest','quest.complete.title':'Flow state','quest.complete.text':'Complete {target} puzzles this week','quest.logic.title':'Pure logic','quest.logic.text':'Win {target} puzzles without hints or smart notes','quest.variants.title':'Explorer','quest.variants.text':'Complete {target} variant puzzles','quest.daily.title':'Daily rhythm','quest.daily.text':'Complete {target} daily challenges','quest.claimed':'Claimed','quest.completeReward':'Weekly quest · +500 XP','progress.level':'Level {level}',
  'settings.colorTheme':'Color theme','settings.boardStyle':'Board style','theme.lavender':'Lavender','theme.ocean':'Ocean','theme.forest':'Forest','theme.sunset':'Sunset','style.classic':'Classic','style.soft':'Soft','style.paper':'Paper','style.neon':'Neon','toast.unlockLevel':'Unlocks at level {level}',
  'pwa.title':'App & offline','pwa.summaryChecking':'Checking app health…','pwa.summaryReady':'Ready for uninterrupted play','pwa.summaryUpdate':'An update is ready','pwa.connection':'Connection','pwa.online':'Online','pwa.offline':'Offline','pwa.cache':'Offline cache','pwa.ready':'Ready','pwa.unavailable':'Unavailable','pwa.version':'Version','pwa.installation':'Installation','pwa.installed':'Installed','pwa.browser':'In browser','pwa.education':'Install Sudodoku for an app-like experience and reliable offline play.','pwa.install':'Install app','pwa.check':'Check for updates','pwa.repair':'Repair offline data','pwa.updateTitle':'A fresh Sudodoku is ready','pwa.updateText':'Update safely without losing your current puzzle.','pwa.updateNow':'Update now','pwa.dismiss':'Dismiss','pwa.updated':'Sudodoku is up to date','pwa.noUpdate':'You already have the latest version','pwa.repaired':'Offline data refreshed','pwa.repairFailed':'Offline repair could not finish','pwa.installUnavailable':'Use your browser menu to install Sudodoku',
  'academy.eyebrow':'Technique Academy','academy.title':'Train your solving eye','academy.lead':'Short, interactive lessons built from real Sudoku positions.','academy.cardTitle':'Read the grid like an expert','academy.settingsHelp':'Practice real patterns with guided lessons','academy.progress':'{completed} of {total} lessons mastered','academy.lessonNumber':'Lesson {number}','academy.mastered':'mastered','academy.masteredLabel':'Mastered','academy.legendPattern':'Pattern','academy.legendElimination':'Elimination','academy.yourTurn':'Your turn','academy.next':'Next lesson','academy.tryAgain':'Not quite. Recheck the highlighted candidates and try again.','academy.lessonComplete':'Lesson mastered','academy.reward':'+{points} focus points earned','academy.level.foundation':'Foundation','academy.level.intermediate':'Intermediate','academy.level.advanced':'Advanced',
  'academy.nakedSingle.title':'Naked single','academy.nakedSingle.intro':'A cell has only one legal candidate left. The answer is visible directly in its notes.','academy.nakedSingle.step1':'Scan the row, column, and box around the highlighted cell.','academy.nakedSingle.step2':'Every digit except 6 is already ruled out by one of those units.','academy.nakedSingle.step3':'Place 6—the cell has no other legal candidate.','academy.nakedSingle.question':'Which digit must go in the highlighted cell?','academy.nakedSingle.success':'Exactly. With every other candidate removed, 6 is forced.',
  'academy.hiddenSingle.title':'Hidden single','academy.hiddenSingle.intro':'A digit may have several candidates in a cell, but only one possible home inside a unit.','academy.hiddenSingle.step1':'Focus on row 1 and track every place where 7 could appear.','academy.hiddenSingle.step2':'Other empty cells in the row cannot accept 7 because of their columns or boxes.','academy.hiddenSingle.step3':'R1C8 is the only home left, so it must contain 7.','academy.hiddenSingle.question':'Which digit is hidden in the highlighted cell?','academy.hiddenSingle.success':'Correct. The 7 is hidden among other candidates, but unique in its row.',
  'academy.nakedPair.title':'Naked pair','academy.nakedPair.intro':'Two cells in one unit contain the same two candidates. Those digits belong to the pair.','academy.nakedPair.step1':'Find the two highlighted cells that share exactly the same candidates.','academy.nakedPair.step2':'Those cells reserve 1 and 8, even though their order is not known yet.','academy.nakedPair.step3':'Remove 1 and 8 from every other candidate list in that unit.','academy.nakedPair.question':'Which candidates form the locked pair?','academy.nakedPair.success':'That’s it. The shared 1 & 8 pair eliminates both digits elsewhere in the unit.',
  'academy.xWing.title':'X-Wing','academy.xWing.intro':'One candidate appears in exactly two matching columns across two rows, forming a rectangle.','academy.xWing.step1':'Find two rows where candidate 7 appears in the same two columns.','academy.xWing.step2':'The 7s must occupy opposite corners of that four-cell rectangle.','academy.xWing.step3':'Eliminate 7 from every other cell in those two columns.','academy.xWing.question':'Which candidate is locked into the X-Wing?','academy.xWing.success':'Excellent. Candidate 7 is locked into the four corners and can be removed along the columns.',
  'backup.title':'Backup & transfer','backup.help':'Export one portable file, then restore it from Sudodoku on another device. Nothing is uploaded.','backup.summary':'{played} games · {achievements} achievements','backup.export':'Export backup','backup.exportHelp':'Save progress and settings','backup.restore':'Restore backup','backup.restoreHelp':'Choose a Sudodoku file','backup.private':'Backups stay readable and entirely under your control.','backup.lastExport':'Last export: {date}','backup.exported':'Portable backup created','backup.reading':'Checking backup integrity…','backup.confirm':'Restore this backup? Current progress and settings on this device will be replaced.','backup.cancelled':'Restore cancelled—nothing changed.','backup.restored':'Backup restored—reloading Sudodoku…','backup.invalid':'This file is not a valid or intact Sudodoku backup.',
  'replay.watch':'Watch replay','replay.timeline':'Solve timeline','replay.title':'Your journey','replay.play':'Play replay','replay.pause':'Pause replay','replay.start':'Starting grid','replay.value':'Placed {value}','replay.erase':'Erased a cell','replay.hint':'Hint placed {value}','replay.snapshot':'Undo','share.cardTitle':'Puzzle complete','share.cardFooter':'Made especially for Edmundas · Sudodoku',
};

const lt = {
  'intro.eyebrow':'Ramesnis galvosūkis','intro.title':'Mąstyk aiškiai.<br><em>Žaisk gražiai.</em>','intro.lead':'Aukščiausios kokybės Sudoku patirtis su apgalvotomis užuominomis, kasdieniais iššūkiais ir įrenginyje saugoma pažanga.','intro.featureOffline':'Veikia be interneto','intro.featureOfflineText':'Žaisk bet kur po pirmojo apsilankymo.','intro.featureCoach':'Švelnios užuominos','intro.featureCoachText':'Aiškios užuominos padeda rasti kitą žingsnį.','intro.featureProgress':'Asmeninė pažanga','intro.featureProgressText':'Augink serijas ir atrakink pasiekimus.','intro.start':'Pradėti pirmą galvosūkį','intro.note':'Kalba ir nuostatos šiame įrenginyje išsaugomos visam laikui.','intro.daily':'Dienos iššūkis','intro.ready':'Laukia tavęs',
  'dedication.label':'Asmeninė dedikacija','dedication.madeFor':'Sukurta specialiai Edmundui','dedication.message':'Rami vieta logikai, susikaupimui ir gražiam mąstymui – sukurta su rūpesčiu.','dedication.footer':'Sukurta Edmundui ir susikaupimo akimirkoms.',
  'settings.personalize':'Pritaikyk sau','settings.title':'Nuostatos','settings.language':'Kalba','settings.languageHelp':'Visam laikui išsaugoma šiame įrenginyje','settings.haptics':'Vibracijos atsakas','settings.hapticsHelp':'Švelni vibracija palaikomuose telefonuose','settings.autoPause':'Automatinė pauzė','settings.autoPauseHelp':'Pristabdyti, kai „Sudodoku“ veikia fone','settings.replayIntro':'Pakartoti pristatymą',
  'game.currentPuzzle':'Dabartinis galvosūkis','game.mistakes':'Klaidos','game.paused':'Žaidimas pristabdytas','game.resume':'Paliesk ir tęsk','game.newGame':'Naujas žaidimas','game.progress':'Galvosūkio pažanga','game.progressText':'{count} iš 81 langelio','mode.classic':'Klasikinis','mode.daily':'Dienos',
  'tools.undo':'Atšaukti','tools.erase':'Ištrinti','tools.notes':'Pastabos','tools.smartNotes':'Išmanios pastabos','tools.hint':'Užuomina','tools.on':'Įj.','tools.off':'Išj.',
  'difficulty.easy':'Lengvas','difficulty.easyMood':'Ramus','difficulty.medium':'Vidutinis','difficulty.mediumMood':'Subalansuotas','difficulty.hard':'Sunkus','difficulty.hardMood':'Susikaupęs','difficulty.expert':'Ekspertas','difficulty.expertMood':'Bebaimis',
  'daily.practice':'Kasdienė praktika','daily.headline':'Atrask savo<br><em>ritmą.</em>','daily.tagline':'Nutildyk triukšmą. Po vieną skaičių.','daily.quote':'Logika nuves nuo A iki B. Vaizduotė nuves visur.','daily.today':'Šiandienos iššūkis','daily.complete':'Dienos užduotis įveikta','daily.play':'Žaisti dabar','daily.replay':'Kartoti','daily.streak':'{count} dienos serija','daily.streakPlural':'{count} dienų serija',
  'hint.title':'{row} eilutė, {column} stulpelis yra {value}','hint.text':'Auksinis langelis atskleistas. Peržvelk jo eilutę, stulpelį ir 3×3 bloką.','hint.revealed':'Užuomina atskleista','hint.look':'Žiūrėk į paryškintą langelį.',
  'footer.focus':'Sukurta susikaupimo akimirkoms.','footer.offline':'Veikia be interneto',
  'result.time':'Laikas','result.score':'Susikaupimo taškai','result.unlocked':'Atrakintas pasiekimas','result.playAnother':'Žaisti dar kartą','result.share':'Dalintis rezultatu','result.complete':'Galvosūkis įveiktas','result.dailyComplete':'Dienos iššūkis įveiktas','result.flawless':'Tobulas susikaupimas.','result.beautiful':'Puikiai padirbėta.','result.dailyText':'Šiandienos tinklelis užbaigtas. Tavo kasdienis ritmas stiprėja.','result.completeText':'Atradai ritmą ir užbaigei galvosūkį.','result.gameOver':'Žaidimas baigtas','result.almost':'Beveik pavyko.','result.failedText':'Trys maži suklydimai. Atsikvėpk ir pradėk iš naujo.',
  'stats.practice':'Tavo praktika','stats.title':'Statistika','stats.played':'Žaista','stats.winRate':'Pergalių dalis','stats.streak':'Serija','stats.best':'Geriausias laikas','stats.points':'Susikaupimo taškai','stats.daily':'Dienos pergalės','stats.achievements':'Pasiekimai','stats.keepPlaying':'Tęsti žaidimą',
  'achievement.first-flow':'Pirmasis ritmas','achievement.clean-grid':'Tobulas sprendimas','achievement.pure-logic':'Gryna logika','achievement.speed-focus':'Mažiau nei 5 min.','achievement.daily-devotion':'Kasdienė ištikimybė','achievement.streak-three':'3 dienų serija','achievement.expert-mind':'Eksperto protas','achievement.new':'Naujas pasiekimas',
  'achievement.first-flow.desc':'Užbaik pirmąjį galvosūkį.','achievement.clean-grid.desc':'Užbaik galvosūkį be klaidų.','achievement.pure-logic.desc':'Laimėk be užuominų ir išmaniųjų pastabų.','achievement.speed-focus.desc':'Užbaik bet kurį žaidimą greičiau nei per 5 minutes.','achievement.daily-devotion.desc':'Užbaik pirmąjį Dienos iššūkį.','achievement.streak-three.desc':'Pasiek 3 dienų Dienos seriją.','achievement.expert-mind.desc':'Užbaik Eksperto galvosūkį.',
  'achievement.explorer':'Visas žemėlapis','achievement.explorer.desc':'Laimėk po kartą Killer, Hyper ir Mini režimuose.','achievement.mini-sprint':'Kišeninis žaibas','achievement.mini-sprint.desc':'Užbaik Mini 6×6 greičiau nei per 90 sekundžių.','achievement.perfect-ten':'Nesudrebinamas','achievement.perfect-ten.desc':'Užbaik 10 galvosūkių iš eilės be klaidų.',
  'achievement.killer-adept':'Narvelių tramdytojas','achievement.killer-adept.desc':'Užbaik 25 Killer galvosūkius.','achievement.hyper-architect':'Hyper architektas','achievement.hyper-architect.desc':'Užbaik 25 Hyper galvosūkius.','achievement.zen-master':'Ramus vanduo','achievement.zen-master.desc':'Užbaik 50 Zen galvosūkių.','achievement.variant-voyager':'Variantų keliautojas','achievement.variant-voyager.desc':'Užbaik 100 variantų galvosūkių.','achievement.logic-fifty':'Grynas protas','achievement.logic-fifty.desc':'Laimėk 50 kartų be užuominų ir išmaniųjų pastabų.','achievement.expert-pure':'Be apsaugos','achievement.expert-pure.desc':'Laimėk 50 Eksperto žaidimų be pagalbos.','achievement.weekly-ten':'Užduočių sergėtojas','achievement.weekly-ten.desc':'Įvykdyk 10 Savaitės užduočių.','achievement.daily-thirty':'Mėnesio ritualas','achievement.daily-thirty.desc':'Pasiek 30 dienų Dienos seriją.','achievement.century':'Šimtuko klubas','achievement.century.desc':'Užbaik 100 galvosūkių.',
  'achievement.perfect-century':'Deimantinis tikslumas','achievement.perfect-century.desc':'Užbaik 100 galvosūkių be klaidų.','achievement.logic-legend':'Logikos legenda','achievement.logic-legend.desc':'Laimėk 250 kartų be pagalbos.','achievement.weekly-fifty':'Nepailstantis tyrinėtojas','achievement.weekly-fifty.desc':'Įvykdyk 50 Savaitės užduočių.','achievement.level-twenty-five':'Susikaupimo viršūnė','achievement.level-twenty-five.desc':'Pasiek 25 pažangos lygį.','achievement.deep-focus':'Gilus susikaupimas','achievement.deep-focus.desc':'Praleisk 100 valandų spręsdamas užbaigtus galvosūkius.','achievement.daily-century':'Šimtas rytų','achievement.daily-century.desc':'Pasiek 100 dienų Dienos seriją.','achievement.year-of-focus':'Susikaupimo metai','achievement.year-of-focus.desc':'Išlaikyk 365 dienų Dienos seriją.','achievement.grandmaster':'Sudodoku didmeistris','achievement.grandmaster.desc':'Užbaik 1 000 galvosūkių.','achievement.level-fifty':'Aukščiau meistriškumo','achievement.level-fifty.desc':'Pasiek 50 pažangos lygį.',
  'achievement.night-owl':'Mėnulio protas','achievement.night-owl.desc':'Užbaik galvosūkį tarp vidurnakčio ir 5 valandos ryto.','achievement.close-call':'Ant ribos','achievement.close-call.desc':'Laimėk padaręs lygiai dvi klaidas.','achievement.no-pencil':'Be pėdsako','achievement.no-pencil.desc':'Užbaik Sunkų arba Eksperto galvosūkį be užuominų ir jokių pastabų.','achievement.patient-mind':'Kantrus protas','achievement.patient-mind.desc':'Spręsk bent 45 minutes ir užbaik be užuominos.',
  'achievement.tier.common':'Dažnas','achievement.tier.rare':'Retas','achievement.tier.epic':'Epinis','achievement.tier.legendary':'Legendinis','achievement.tier.mythic':'Mitinis','achievement.tier.secret':'Slaptas','achievement.completed':'Įvykdyta','achievement.hours':'val.','achievement.multiple':'Atrakinta pasiekimų: {count}','achievement.secret':'Slaptas pasiekimas','achievement.secret.desc':'Sąlyga lieka paslėpta, kol pasiekimas atrakinamas.','achievement.hidden':'Paslėpta','achievement.history':'Pasiekimų istorija','achievement.historyEmpty':'Būsimi tavo pasiekimai atsiras čia.','achievement.unlockedEvent':'Atrakintas pasiekimas','achievement.almostThere':'Tikslas jau arti','achievement.styleUnlocked':'Atrakintas naujas stilius','achievement.progressEvent':'Įvykdyta {current} iš {target}','achievement.historyCount':'Gauta: {count}',
  'toast.restored':'Sveikas sugrįžęs — žaidimas atkurtas','toast.creating':'Kuriamas naujas galvosūkis…','toast.dailyReady':'Šiandienos iššūkis paruoštas','toast.puzzleReady':'Paruoštas: {difficulty}','toast.smartNotes':'Pažymėti {count} galimi skaičiai','toast.shared':'Rezultatu pasidalinta','toast.copied':'Rezultatas nukopijuotas','toast.cardSaved':'Rezultato kortelė išsaugota','toast.offlineLater':'Režimas be interneto veiks kitą kartą','toast.languageSaved':'Kalba išsaugota visam laikui',
  'share.text':'Sudodoku {difficulty} · {time} · klaidos: {mistakes} · susikaupimo taškai: {score}','share.title':'Mano „Sudodoku“ rezultatas',
  'common.notNow':'Ne dabar','common.done':'Atlikta','common.settings':'Nuostatos','common.statistics':'Statistika','common.sound':'Garsas','common.theme':'Tema','common.pause':'Pristabdyti žaidimą','common.language':'Kalba',
  'game.progressOf':'{count} iš {total} langelių','mode.classicHelp':'Nesenstantis 9×9 žaidimas','mode.killer':'Killer','mode.killerHelp':'Narveliai ir sumos','mode.hyper':'Hyper','mode.hyperHelp':'Keturi papildomi regionai','mode.mini':'Mini 6×6','mode.miniHelp':'Trumpas susikaupimas','mode.zen':'Zen','mode.zenHelp':'Be laiko ir klaidų',
  'unit.row':'{number} eilutėje','unit.column':'{number} stulpelyje','unit.box':'{number} bloke','unit.hyper':'{number} hyper regione',
  'technique.nakedSingle.title':'Vienintelis kandidatas · R{row}C{column} = {value}','technique.nakedSingle.text':'Šiame langelyje gali būti tik {value}. Visus kitus kandidatus atmeta eilutė, stulpelis arba blokas.','technique.hiddenSingle.title':'Paslėptas vienintelis · {value}','technique.hiddenSingle.text':'{unitLabel} skaičius {value} gali būti tik langelyje {cellsLabel}.','technique.nakedPair.title':'Atvira pora · {pairLabel}','technique.nakedPair.text':'{cellsLabel} rezervuoja {pairLabel} – šiuos kandidatus galima pašalinti iš {targetsLabel}.','technique.xWing.title':'X-Wing · kandidatas {value}','technique.xWing.text':'Keturi kampai {cellsLabel} užfiksuoja {value}, todėl jis pašalinamas iš {targetsLabel}.','technique.reveal.title':'Atskleidimas · R{row}C{column} = {value}','technique.reveal.text':'Nerasta palaikoma vienintelio kandidato, poros ar X-Wing technika, todėl atskleidžiamas šis langelis.',
  'quest.weekly':'Savaitės užduotis','quest.complete.title':'Ritmo būsena','quest.complete.text':'Šią savaitę užbaik {target} galvosūkius','quest.logic.title':'Gryna logika','quest.logic.text':'Laimėk {target} kartus be užuominų','quest.variants.title':'Tyrinėtojas','quest.variants.text':'Užbaik {target} variantų žaidimus','quest.daily.title':'Kasdienis ritmas','quest.daily.text':'Užbaik {target} dienos iššūkius','quest.claimed':'Gauta','quest.completeReward':'Savaitės užduotis · +500 XP','progress.level':'{level} lygis',
  'settings.colorTheme':'Spalvų tema','settings.boardStyle':'Lentos stilius','theme.lavender':'Levandų','theme.ocean':'Vandenyno','theme.forest':'Miško','theme.sunset':'Saulėlydžio','style.classic':'Klasikinis','style.soft':'Švelnus','style.paper':'Popierius','style.neon':'Neonas','toast.unlockLevel':'Atsirakina {level} lygyje',
  'pwa.title':'Programėlė ir ryšys','pwa.summaryChecking':'Tikrinama programėlės būsena…','pwa.summaryReady':'Paruošta nepertraukiamam žaidimui','pwa.summaryUpdate':'Paruoštas atnaujinimas','pwa.connection':'Ryšys','pwa.online':'Prisijungta','pwa.offline':'Be interneto','pwa.cache':'Duomenys be ryšio','pwa.ready':'Paruošta','pwa.unavailable':'Nepasiekiama','pwa.version':'Versija','pwa.installation':'Įdiegimas','pwa.installed':'Įdiegta','pwa.browser':'Naršyklėje','pwa.education':'Įdiek „Sudodoku“ kaip programėlę ir patikimai žaisk be interneto.','pwa.install':'Įdiegti','pwa.check':'Tikrinti naujinius','pwa.repair':'Atkurti duomenis','pwa.updateTitle':'Paruošta nauja „Sudodoku“ versija','pwa.updateText':'Atnaujink saugiai – dabartinis galvosūkis nedings.','pwa.updateNow':'Atnaujinti','pwa.dismiss':'Uždaryti','pwa.updated':'„Sudodoku“ atnaujinta','pwa.noUpdate':'Jau naudoji naujausią versiją','pwa.repaired':'Duomenys be interneto atnaujinti','pwa.repairFailed':'Nepavyko atkurti duomenų','pwa.installUnavailable':'Įdiek „Sudodoku“ per naršyklės meniu',
  'academy.eyebrow':'Technikų akademija','academy.title':'Lavink sprendėjo žvilgsnį','academy.lead':'Trumpos interaktyvios pamokos iš tikrų Sudoku situacijų.','academy.cardTitle':'Skaityk tinklelį kaip ekspertas','academy.settingsHelp':'Mokykis tikrų raštų su vedamomis pamokomis','academy.progress':'Įveikta {completed} iš {total} pamokų','academy.lessonNumber':'{number} pamoka','academy.mastered':'įvaldyta','academy.masteredLabel':'Įvaldyta','academy.legendPattern':'Raštas','academy.legendElimination':'Atmetimas','academy.yourTurn':'Tavo eilė','academy.next':'Kita pamoka','academy.tryAgain':'Dar ne. Peržvelk paryškintus kandidatus ir bandyk dar kartą.','academy.lessonComplete':'Pamoka įvaldyta','academy.reward':'Gauta susikaupimo taškų: {points}','academy.level.foundation':'Pagrindai','academy.level.intermediate':'Vidutinis','academy.level.advanced':'Pažengęs',
  'academy.nakedSingle.title':'Vienintelis kandidatas','academy.nakedSingle.intro':'Langelyje liko tik vienas galimas kandidatas. Atsakymas tiesiogiai matomas pastabose.','academy.nakedSingle.step1':'Peržvelk paryškinto langelio eilutę, stulpelį ir bloką.','academy.nakedSingle.step2':'Visus skaičius, išskyrus 6, jau atmeta viena iš šių sričių.','academy.nakedSingle.step3':'Įrašyk 6 – jokio kito teisėto kandidato nėra.','academy.nakedSingle.question':'Kuris skaičius turi būti paryškintame langelyje?','academy.nakedSingle.success':'Teisingai. Atmetus visus kitus kandidatus, 6 yra privalomas.',
  'academy.hiddenSingle.title':'Paslėptas vienintelis','academy.hiddenSingle.intro':'Langelyje gali būti keli kandidatai, tačiau srityje skaičiui gali likti tik viena vieta.','academy.hiddenSingle.step1':'Sutelk dėmesį į 1 eilutę ir rask visas vietas, kur galėtų būti 7.','academy.hiddenSingle.step2':'Kiti tušti eilutės langeliai negali priimti 7 dėl savo stulpelių ar blokų.','academy.hiddenSingle.step3':'R1C8 yra vienintelė likusi vieta, todėl joje turi būti 7.','academy.hiddenSingle.question':'Kuris skaičius paslėptas paryškintame langelyje?','academy.hiddenSingle.success':'Teisingai. 7 slepiasi tarp kitų kandidatų, bet eilutėje yra vienintelis.',
  'academy.nakedPair.title':'Atvira pora','academy.nakedPair.intro':'Du vienos srities langeliai turi tuos pačius du kandidatus. Šie skaičiai priklauso porai.','academy.nakedPair.step1':'Rask du paryškintus langelius su visiškai vienodais kandidatais.','academy.nakedPair.step2':'Šie langeliai rezervuoja 1 ir 8, nors jų tvarka dar nežinoma.','academy.nakedPair.step3':'Pašalink 1 ir 8 iš visų kitų tos srities kandidatų sąrašų.','academy.nakedPair.question':'Kurie kandidatai sudaro užrakintą porą?','academy.nakedPair.success':'Puiku. Bendra 1 ir 8 pora pašalina abu skaičius kitose srities vietose.',
  'academy.xWing.title':'X-Wing','academy.xWing.intro':'Vienas kandidatas dviejose eilutėse pasirodo tik tuose pačiuose dviejuose stulpeliuose ir sudaro stačiakampį.','academy.xWing.step1':'Rask dvi eilutes, kuriose kandidatas 7 yra tuose pačiuose dviejuose stulpeliuose.','academy.xWing.step2':'Septynetai turi užimti priešingus keturių langelių stačiakampio kampus.','academy.xWing.step3':'Pašalink 7 iš visų kitų tų dviejų stulpelių langelių.','academy.xWing.question':'Kuris kandidatas užrakintas X-Wing rašte?','academy.xWing.success':'Puikiai. Kandidatas 7 užrakintas keturiuose kampuose ir gali būti pašalintas iš stulpelių.',
  'backup.title':'Atsarginė kopija ir perkėlimas','backup.help':'Eksportuok vieną failą ir atkurk jį „Sudodoku“ kitame įrenginyje. Niekas nesiunčiama į internetą.','backup.summary':'Žaidimų: {played} · pasiekimų: {achievements}','backup.export':'Eksportuoti kopiją','backup.exportHelp':'Išsaugoti pažangą ir nuostatas','backup.restore':'Atkurti kopiją','backup.restoreHelp':'Pasirinkti „Sudodoku“ failą','backup.private':'Kopija lieka skaitoma ir visiškai tavo valdoma.','backup.lastExport':'Paskutinė kopija: {date}','backup.exported':'Perkeliama kopija sukurta','backup.reading':'Tikrinamas kopijos vientisumas…','backup.confirm':'Atkurti šią kopiją? Dabartinė šio įrenginio pažanga ir nuostatos bus pakeistos.','backup.cancelled':'Atkūrimas atšauktas – niekas nepakeista.','backup.restored':'Kopija atkurta – „Sudodoku“ paleidžiama iš naujo…','backup.invalid':'Tai nėra tinkama arba nepažeista „Sudodoku“ kopija.',
  'replay.watch':'Žiūrėti pakartojimą','replay.timeline':'Sprendimo eiga','replay.title':'Tavo kelionė','replay.play':'Leisti pakartojimą','replay.pause':'Pristabdyti pakartojimą','replay.start':'Pradinis tinklelis','replay.value':'Įrašyta {value}','replay.erase':'Ištrintas langelis','replay.hint':'Užuomina įrašė {value}','replay.snapshot':'Atšaukimas','share.cardTitle':'Galvosūkis įveiktas','share.cardFooter':'Sukurta specialiai Edmundui · Sudodoku',
};

const es = {
  ...en,
  'intro.eyebrow':'Un rompecabezas más sereno','intro.title':'Piensa con claridad.<br><em>Juega con estilo.</em>','intro.lead':'Una experiencia Sudoku premium con pistas útiles, retos diarios y progreso guardado en tu dispositivo.','intro.featureOffline':'Realmente sin conexión','intro.featureOfflineText':'Juega donde quieras después de tu primera visita.','intro.featureCoach':'Ayuda amable','intro.featureCoachText':'Las pistas visibles te ayudan con el siguiente paso.','intro.featureProgress':'Progreso personal','intro.featureProgressText':'Crea rachas y desbloquea logros.','intro.start':'Comenzar mi primer puzzle','intro.note':'Tu idioma y preferencias se guardan permanentemente en este dispositivo.','settings.personalize':'Hazlo tuyo','settings.title':'Ajustes','settings.language':'Idioma','settings.languageHelp':'Guardado permanentemente en este dispositivo','settings.haptics':'Respuesta háptica','settings.autoPause':'Pausa automática','settings.replayIntro':'Repetir introducción','game.currentPuzzle':'Puzzle actual','game.mistakes':'Errores','game.paused':'Juego en pausa','game.resume':'Toca para continuar','game.newGame':'Nueva partida','game.progress':'Progreso','game.progressText':'{count} de 81 celdas','mode.classic':'Clásico','mode.daily':'Diario','tools.undo':'Deshacer','tools.erase':'Borrar','tools.notes':'Notas','tools.smartNotes':'Notas inteligentes','tools.hint':'Pista','tools.on':'Sí','tools.off':'No','difficulty.easy':'Fácil','difficulty.medium':'Medio','difficulty.hard':'Difícil','difficulty.expert':'Experto','daily.practice':'Práctica diaria','daily.headline':'Encuentra tu<br><em>ritmo.</em>','daily.today':'Reto de hoy','daily.complete':'Reto completado','daily.play':'Jugar ahora','daily.replay':'Repetir','daily.streak':'Racha de {count} día','daily.streakPlural':'Racha de {count} días','hint.title':'Fila {row}, columna {column}: {value}','hint.text':'La celda dorada está revelada. Revisa su fila, columna y bloque 3×3.','footer.focus':'Hecho para momentos de concentración.','footer.offline':'Listo sin conexión','result.time':'Tiempo','result.score':'Puntos de enfoque','result.unlocked':'Logro desbloqueado','result.playAnother':'Jugar otra','result.share':'Compartir resultado','result.complete':'Puzzle completado','result.dailyComplete':'Reto diario completado','result.flawless':'Concentración perfecta.','result.beautiful':'Excelente.','result.gameOver':'Fin del juego','result.almost':'Casi lo tienes.','stats.practice':'Tu práctica','stats.title':'Estadísticas','stats.played':'Jugadas','stats.winRate':'Victorias','stats.streak':'Racha','stats.best':'Mejor tiempo','stats.points':'Puntos','stats.daily':'Retos diarios','stats.achievements':'Logros','stats.keepPlaying':'Seguir jugando','common.notNow':'Ahora no','common.done':'Listo','toast.languageSaved':'Idioma guardado permanentemente',
};

const de = {
  ...en,
  'intro.eyebrow':'Ein ruhigeres Rätsel','intro.title':'Denke klar.<br><em>Spiele stilvoll.</em>','intro.lead':'Ein erstklassiges Sudoku-Erlebnis mit hilfreichen Hinweisen, täglichen Aufgaben und lokalem Fortschritt.','intro.featureOffline':'Wirklich offline','intro.featureOfflineText':'Spiele nach dem ersten Besuch überall.','intro.featureCoach':'Sanfte Hilfe','intro.featureCoachText':'Sichtbare Hinweise zeigen den nächsten Schritt.','intro.featureProgress':'Dein Fortschritt','intro.featureProgressText':'Baue Serien auf und schalte Erfolge frei.','intro.start':'Erstes Rätsel beginnen','intro.note':'Sprache und Einstellungen bleiben auf diesem Gerät gespeichert.','settings.personalize':'Mach es zu deinem','settings.title':'Einstellungen','settings.language':'Sprache','settings.languageHelp':'Dauerhaft auf diesem Gerät gespeichert','settings.haptics':'Haptisches Feedback','settings.autoPause':'Automatisch pausieren','settings.replayIntro':'Einführung wiederholen','game.currentPuzzle':'Aktuelles Rätsel','game.mistakes':'Fehler','game.paused':'Spiel pausiert','game.resume':'Tippen zum Fortsetzen','game.newGame':'Neues Spiel','game.progress':'Fortschritt','game.progressText':'{count} von 81 Feldern','mode.classic':'Klassisch','mode.daily':'Täglich','tools.undo':'Zurück','tools.erase':'Löschen','tools.notes':'Notizen','tools.smartNotes':'Smarte Notizen','tools.hint':'Hinweis','tools.on':'An','tools.off':'Aus','difficulty.easy':'Leicht','difficulty.medium':'Mittel','difficulty.hard':'Schwer','difficulty.expert':'Experte','daily.practice':'Tägliche Übung','daily.headline':'Finde deinen<br><em>Flow.</em>','daily.today':'Heutige Aufgabe','daily.complete':'Tagesaufgabe geschafft','daily.play':'Jetzt spielen','daily.replay':'Nochmal','daily.streak':'{count} Tag Serie','daily.streakPlural':'{count} Tage Serie','hint.title':'Zeile {row}, Spalte {column} ist {value}','hint.text':'Das goldene Feld ist aufgedeckt. Prüfe Zeile, Spalte und 3×3-Block.','footer.focus':'Für Momente voller Fokus.','footer.offline':'Offline bereit','result.time':'Zeit','result.score':'Fokuspunkte','result.unlocked':'Erfolg freigeschaltet','result.playAnother':'Noch einmal','result.share':'Ergebnis teilen','result.complete':'Rätsel gelöst','result.dailyComplete':'Tagesaufgabe gelöst','result.flawless':'Makelloser Fokus.','result.beautiful':'Wundervoll gelöst.','result.gameOver':'Spiel vorbei','result.almost':'Fast geschafft.','stats.practice':'Deine Übung','stats.title':'Statistik','stats.played':'Gespielt','stats.winRate':'Siegquote','stats.streak':'Serie','stats.best':'Bestzeit','stats.points':'Fokuspunkte','stats.daily':'Tagessiege','stats.achievements':'Erfolge','stats.keepPlaying':'Weiterspielen','common.notNow':'Nicht jetzt','common.done':'Fertig','toast.languageSaved':'Sprache dauerhaft gespeichert',
};

const uk = {
  ...en,
  'intro.eyebrow':'Спокійніша головоломка','intro.title':'Думай ясно.<br><em>Грай красиво.</em>','intro.lead':'Преміальний Sudoku з продуманими підказками, щоденними викликами та прогресом на вашому пристрої.','intro.featureOffline':'Повністю офлайн','intro.featureOfflineText':'Грайте будь-де після першого візиту.','intro.featureCoach':'Делікатні підказки','intro.featureCoachText':'Помітні підказки допомагають знайти наступний крок.','intro.featureProgress':'Особистий прогрес','intro.featureProgressText':'Будуйте серії та відкривайте досягнення.','intro.start':'Почати першу головоломку','intro.note':'Мова й налаштування постійно зберігаються на цьому пристрої.','settings.personalize':'Налаштуйте під себе','settings.title':'Налаштування','settings.language':'Мова','settings.languageHelp':'Постійно зберігається на цьому пристрої','settings.haptics':'Вібровідгук','settings.autoPause':'Автоматична пауза','settings.replayIntro':'Повторити знайомство','game.currentPuzzle':'Поточна головоломка','game.mistakes':'Помилки','game.paused':'Гру призупинено','game.resume':'Торкніться, щоб продовжити','game.newGame':'Нова гра','game.progress':'Прогрес','game.progressText':'{count} з 81 клітинки','mode.classic':'Класика','mode.daily':'Щоденна','tools.undo':'Скасувати','tools.erase':'Стерти','tools.notes':'Нотатки','tools.smartNotes':'Розумні нотатки','tools.hint':'Підказка','tools.on':'Увім.','tools.off':'Вимк.','difficulty.easy':'Легко','difficulty.medium':'Середньо','difficulty.hard':'Складно','difficulty.expert':'Експерт','daily.practice':'Щоденна практика','daily.headline':'Знайди свій<br><em>ритм.</em>','daily.today':'Виклик дня','daily.complete':'Виклик виконано','daily.play':'Грати','daily.replay':'Повторити','daily.streak':'Серія: {count} день','daily.streakPlural':'Серія: {count} днів','hint.title':'Рядок {row}, стовпець {column}: {value}','hint.text':'Золоту клітинку відкрито. Перегляньте її рядок, стовпець і блок 3×3.','footer.focus':'Створено для моментів зосередженості.','footer.offline':'Працює офлайн','result.time':'Час','result.score':'Бали фокусу','result.unlocked':'Досягнення відкрито','result.playAnother':'Грати ще','result.share':'Поділитися','result.complete':'Головоломку завершено','result.dailyComplete':'Щоденний виклик виконано','result.flawless':'Бездоганний фокус.','result.beautiful':'Чудова робота.','result.gameOver':'Гру завершено','result.almost':'Майже вдалося.','stats.practice':'Ваша практика','stats.title':'Статистика','stats.played':'Зіграно','stats.winRate':'Перемоги','stats.streak':'Серія','stats.best':'Кращий час','stats.points':'Бали фокусу','stats.daily':'Щоденні перемоги','stats.achievements':'Досягнення','stats.keepPlaying':'Продовжити','common.notNow':'Не зараз','common.done':'Готово','toast.languageSaved':'Мову збережено назавжди',
};

const dictionaries = { en, lt, es, de, uk };

export function translate(locale, key, variables = {}) {
  const template = dictionaries[locale]?.[key] ?? en[key] ?? key;
  return String(template).replace(/\{(\w+)\}/g, (_, name) => variables[name] ?? `{${name}}`);
}

export function applyDocumentTranslations(locale) {
  document.documentElement.lang = locale;
  document.querySelectorAll('[data-i18n]').forEach((element) => { element.textContent = translate(locale, element.dataset.i18n); });
  document.querySelectorAll('[data-i18n-html]').forEach((element) => { element.innerHTML = translate(locale, element.dataset.i18nHtml); });
}
