export const LOCALES = [
  { code: 'en', name: 'English' },
  { code: 'lt', name: 'Lietuvių' },
  { code: 'es', name: 'Español' },
  { code: 'de', name: 'Deutsch' },
  { code: 'uk', name: 'Українська' },
];

const en = {
  'languageLaunch.eyebrow':'Welcome · Sveiki · Bienvenido','languageLaunch.title':'Choose your language','languageLaunch.lead':'Choose the language you want Sudodoku to remember on this device.','languageLaunch.selected':'Selected: {language}','languageLaunch.continue':'Continue','languageLaunch.changeAnytime':'You can change this anytime in Settings.',
  'intro.eyebrow':'A calmer kind of puzzle','intro.title':'Think clearly.<br><em>Play beautifully.</em>','intro.lead':'A premium Sudoku ritual with thoughtful hints, daily challenges and progress that stays on your device.','intro.featureOffline':'Truly offline','intro.featureOfflineText':'Play anywhere after your first visit.','intro.featureCoach':'Gentle coaching','intro.featureCoachText':'Visible hints help you find the next step.','intro.featureProgress':'Personal progress','intro.featureProgressText':'Build streaks and unlock achievements.','intro.start':'Begin your first puzzle','intro.note':'Your language and preferences are saved permanently on this device.','intro.daily':'Daily challenge','intro.ready':'Ready when you are',
  'dedication.label':'A personal dedication','dedication.madeFor':'Made especially for Edmundas','dedication.message':'A quiet place for logic, focus, and beautiful thinking—created with care.','dedication.footer':'Made for Edmundas, for moments of focus.','dedication.short':'For Edmundas',
  'mainMenu.personal':'Your Sudoku space','mainMenu.welcome':'Welcome back.<br><em>Find your flow.</em>','mainMenu.lead':'Your quiet place for logic, focus, and a beautifully clear mind.','mainMenu.continue':'Continue puzzle','mainMenu.startFresh':'Start a new puzzle','mainMenu.progress':'{percent}% complete','mainMenu.ready':'Ready when you are','mainMenu.newPuzzle':'New puzzle','mainMenu.choose':'Choose your next flow','mainMenu.dailyHelp':'Today’s shared challenge','mainMenu.yourJourney':'Your journey','mainMenu.forEdmundas':'Made for Edmundas','mainMenu.statsHelp':'See streaks and achievements','mainMenu.settingsHelp':'Themes, backup, and language','mainMenu.open':'Go to main menu',
  'settings.personalize':'Make it yours','settings.title':'Settings','settings.language':'Language','settings.languageHelp':'Saved permanently on this device','settings.haptics':'Haptic feedback','settings.hapticsHelp':'Gentle vibration on supported phones','settings.autoPause':'Automatic pause','settings.autoPauseHelp':'Pause when Sudodoku moves to the background','settings.replayIntro':'Replay introduction',
  'game.currentPuzzle':'Current puzzle','game.mistakes':'Mistakes','game.paused':'Game paused','game.resume':'Tap to find your flow','game.newGame':'New game','game.progress':'Puzzle progress','game.progressText':'{count} of 81 cells','mode.classic':'Classic','mode.daily':'Daily',
  'tools.undo':'Undo','tools.erase':'Erase','tools.notes':'Notes','tools.smartNotes':'Smart notes','tools.hint':'Hint','tools.on':'On','tools.off':'Off',
  'difficulty.easy':'Easy','difficulty.easyMood':'Relaxed','difficulty.medium':'Medium','difficulty.mediumMood':'Balanced','difficulty.hard':'Hard','difficulty.hardMood':'Focused','difficulty.expert':'Expert','difficulty.expertMood':'Fearless',
  'daily.practice':'Daily practice','daily.headline':'Find your<br><em>flow.</em>','daily.tagline':'Quiet the noise. One number at a time.','daily.quote':'Logic will get you from A to B. Imagination will take you everywhere.','daily.today':'Today’s challenge','daily.complete':'Daily complete','daily.play':'Play now','daily.replay':'Replay','daily.streak':'{count} day streak','daily.streakPlural':'{count} day streak',
  'hint.title':'Row {row}, column {column} is {value}','hint.text':'The golden cell is revealed. Scan its row, column and 3×3 box to see what this unlocks.','hint.revealed':'Hint revealed','hint.look':'Look at the highlighted cell.',
  'footer.focus':'Made for moments of focus.','footer.offline':'Offline ready',
  'result.time':'Time','result.score':'Focus score','result.unlocked':'Achievement unlocked','result.playAnother':'Play another','result.share':'Share result','result.complete':'Puzzle complete','result.dailyComplete':'Daily challenge complete','result.flawless':'Flawless focus.','result.beautiful':'Beautifully done.','result.dailyText':'Today’s grid is complete. Your daily rhythm is growing.','result.completeText':'You found your flow and finished the puzzle.','result.gameOver':'Game over','result.almost':'Almost there.','result.failedText':'Three little slips. Take a breath and begin again.',
  'stats.practice':'Your practice','stats.title':'Statistics','stats.played':'Played','stats.winRate':'Win rate','stats.streak':'Streak','stats.best':'Best time','stats.points':'Focus points','stats.daily':'Daily wins','stats.achievements':'Achievements','stats.keepPlaying':'Keep playing',
  'achievement.first-flow':'First flow','achievement.clean-grid':'Perfect solve','achievement.pure-logic':'Pure logic','achievement.speed-focus':'Under 5 min','achievement.daily-devotion':'Daily devotion','achievement.streak-three':'3 day streak','achievement.expert-mind':'Expert mind','achievement.new':'New milestone',
  'achievement.first-flow.desc':'Complete your first puzzle.','achievement.clean-grid.desc':'Finish a puzzle without a mistake.','achievement.pure-logic.desc':'Win without hints or smart notes.','achievement.speed-focus.desc':'Finish any timed puzzle in under 5 minutes.','achievement.daily-devotion.desc':'Complete your first Daily challenge.','achievement.streak-three.desc':'Reach a 3-day Daily streak.','achievement.expert-mind.desc':'Complete an Expert puzzle.',
  'achievement.explorer':'Across the map','achievement.explorer.desc':'Win once in Killer, Hyper, and Mini.','achievement.mini-sprint':'Pocket lightning','achievement.mini-sprint.desc':'Finish Mini 6×6 in under 90 seconds.','achievement.perfect-ten':'Unshaken','achievement.perfect-ten.desc':'Complete 10 perfect puzzles in a row.',
  'achievement.academy-initiate':'Pattern apprentice','achievement.academy-initiate.desc':'Master 4 Technique Academy lessons.','achievement.academy-scholar':'Academy scholar','achievement.academy-scholar.desc':'Master 8 Technique Academy lessons.','achievement.fish-school':'Fish spotter','achievement.fish-school.desc':'Master both X-Wing and Swordfish.','achievement.academy-master':'Academy master','achievement.academy-master.desc':'Master every Technique Academy lesson.','achievement.pattern-voyager':'Pattern voyager','achievement.pattern-voyager.desc':'Discover 6 distinct solving techniques.','achievement.logical-guide':'Logical guide','achievement.logical-guide.desc':'Use 100 technique-aware hints.','achievement.technique-librarian':'Technique librarian','achievement.technique-librarian.desc':'Discover every Academy technique.','achievement.deduction-sage':'Deduction sage','achievement.deduction-sage.desc':'Use 1,000 technique-aware hints—a truly long-term feat.',
  'achievement.killer-adept':'Cage breaker','achievement.killer-adept.desc':'Complete 25 Killer puzzles.','achievement.hyper-architect':'Hyper architect','achievement.hyper-architect.desc':'Complete 25 Hyper puzzles.','achievement.zen-master':'Still water','achievement.zen-master.desc':'Complete 50 Zen puzzles.','achievement.variant-voyager':'Variant voyager','achievement.variant-voyager.desc':'Complete 100 variant puzzles.','achievement.logic-fifty':'Pure reason','achievement.logic-fifty.desc':'Win 50 puzzles without hints or smart notes.','achievement.expert-pure':'No safety net','achievement.expert-pure.desc':'Win 50 Expert puzzles without help.','achievement.weekly-ten':'Quest keeper','achievement.weekly-ten.desc':'Complete 10 Weekly quests.','achievement.daily-thirty':'Monthly ritual','achievement.daily-thirty.desc':'Reach a 30-day Daily streak.','achievement.century':'Century club','achievement.century.desc':'Complete 100 puzzles.',
  'achievement.perfect-century':'Diamond precision','achievement.perfect-century.desc':'Complete 100 puzzles without a mistake.','achievement.logic-legend':'Logic legend','achievement.logic-legend.desc':'Win 250 puzzles without help.','achievement.weekly-fifty':'Relentless explorer','achievement.weekly-fifty.desc':'Complete 50 Weekly quests.','achievement.level-twenty-five':'Focused ascent','achievement.level-twenty-five.desc':'Reach progression level 25.','achievement.deep-focus':'Deep focus','achievement.deep-focus.desc':'Spend 100 hours solving completed puzzles.','achievement.daily-century':'Hundred mornings','achievement.daily-century.desc':'Reach a 100-day Daily streak.','achievement.year-of-focus':'Year of focus','achievement.year-of-focus.desc':'Maintain a 365-day Daily streak.','achievement.grandmaster':'Sudodoku grandmaster','achievement.grandmaster.desc':'Complete 1,000 puzzles.','achievement.level-fifty':'Beyond mastery','achievement.level-fifty.desc':'Reach progression level 50.',
  'achievement.night-owl':'Moonlit mind','achievement.night-owl.desc':'Complete a puzzle between midnight and 5 a.m.','achievement.close-call':'On the edge','achievement.close-call.desc':'Win after making exactly two mistakes.','achievement.no-pencil':'Without a trace','achievement.no-pencil.desc':'Complete a Hard or Expert puzzle without hints or any notes.','achievement.patient-mind':'Patient mind','achievement.patient-mind.desc':'Solve for at least 45 minutes and finish without a hint.',
  'achievement.tier.common':'Common','achievement.tier.rare':'Rare','achievement.tier.epic':'Epic','achievement.tier.legendary':'Legendary','achievement.tier.mythic':'Mythic','achievement.tier.secret':'Secret','achievement.completed':'Completed','achievement.hours':'hours','achievement.multiple':'{count} achievements unlocked','achievement.secret':'Secret achievement','achievement.secret.desc':'Its requirement remains hidden until you unlock it.','achievement.hidden':'Hidden','achievement.history':'Achievement history','achievement.historyEmpty':'Your future milestones will appear here.','achievement.unlockedEvent':'Achievement unlocked','achievement.almostThere':'Milestone within reach','achievement.styleUnlocked':'New style unlocked','achievement.progressEvent':'{current} of {target} complete','achievement.historyCount':'{count} earned',
  'toast.restored':'Game restored — ready to continue','toast.creating':'Creating a fresh puzzle…','toast.dailyReady':'Today’s challenge is ready','toast.puzzleReady':'{difficulty} puzzle ready','toast.smartNotes':'Smart notes mapped {count} candidates','toast.smartNotesOn':'Smart notes on · {count} candidates mapped','toast.smartNotesOff':'Smart notes off · generated candidates cleared','toast.shared':'Result shared','toast.copied':'Result copied','toast.cardSaved':'Result card saved','toast.offlineLater':'Offline mode will be ready next time','toast.languageSaved':'Language saved permanently',
  'share.text':'Sudodoku {difficulty} · {time} · {mistakes} mistakes · {score} focus points','share.title':'My Sudodoku result',
  'common.notNow':'Not now','common.done':'Done','common.settings':'Settings','common.statistics':'Statistics','common.sound':'Sound','common.theme':'Theme','common.pause':'Pause game','common.language':'Language',
  'game.progressOf':'{count} of {total} cells','mode.classicHelp':'The timeless 9×9 game','mode.killer':'Killer','mode.killerHelp':'Cages and sums','mode.hyper':'Hyper','mode.hyperHelp':'Four extra regions','mode.mini':'Mini 6×6','mode.miniHelp':'Quick, compact focus','mode.zen':'Zen','mode.zenHelp':'No timer or mistakes',
  'unit.row':'row {number}','unit.column':'column {number}','unit.box':'box {number}','unit.hyper':'hyper region {number}',
  'technique.nakedSingle.title':'Naked single · R{row}C{column} = {value}','technique.nakedSingle.text':'Only {value} can legally fit this cell. Every other candidate is already present in its row, column or box.','technique.hiddenSingle.title':'Hidden single · {value}','technique.hiddenSingle.text':'In {unitLabel}, {value} can appear only at {cellsLabel}.','technique.nakedPair.title':'Naked pair · {pairLabel}','technique.nakedPair.text':'{cellsLabel} reserve {pairLabel} in {unitLabel}, so those candidates are removed from {targetsLabel}.','technique.pointingPair.title':'Pointing candidates · {value}','technique.pointingPair.text':'Inside {unitLabel}, every {value} lies on one line, so {value} can be removed from {targetsLabel} outside the box.','technique.boxLineReduction.title':'Box/line reduction · {value}','technique.boxLineReduction.text':'All {value}s on this line fall inside one box, removing {value} from {targetsLabel} elsewhere in that box.','technique.hiddenPair.title':'Hidden pair · {pairLabel}','technique.hiddenPair.text':'Only {cellsLabel} can hold {pairLabel} in {unitLabel}; other candidates are removed from those cells.','technique.nakedTriple.title':'Naked triple · {valuesLabel}','technique.nakedTriple.text':'Three cells in {unitLabel} reserve {valuesLabel}, eliminating those digits from {targetsLabel}.','technique.hiddenTriple.title':'Hidden triple · {valuesLabel}','technique.hiddenTriple.text':'Only three cells in {unitLabel} can hold {valuesLabel}, so their other candidates can be removed.','technique.xWing.title':'X-Wing · candidate {value}','technique.xWing.text':'The four corners at {cellsLabel} lock {value} across lines {linesLabel}, eliminating it from {targetsLabel}.','technique.xyWing.title':'XY-Wing · eliminate {value}','technique.xyWing.text':'The pivot and two pincers at {cellsLabel} force one pincer to contain {value}, eliminating it from {targetsLabel}.','technique.skyscraper.title':'Skyscraper · candidate {value}','technique.skyscraper.text':'Two offset strong links on lines {linesLabel} force one roof to contain {value}, eliminating it from {targetsLabel}.','technique.swordfish.title':'Swordfish · candidate {value}','technique.swordfish.text':'Three lines confine {value} to three crossing lines, eliminating it from {targetsLabel}.','technique.reveal.title':'Guided reveal · R{row}C{column} = {value}','technique.reveal.text':'No supported logical pattern is currently available, so this cell is revealed to keep your solve moving.',
  'quest.weekly':'Weekly quest','quest.complete.title':'Flow state','quest.complete.text':'Complete {target} puzzles this week','quest.logic.title':'Pure logic','quest.logic.text':'Win {target} puzzles without hints or smart notes','quest.variants.title':'Explorer','quest.variants.text':'Complete {target} variant puzzles','quest.daily.title':'Daily rhythm','quest.daily.text':'Complete {target} daily challenges','quest.claimed':'Claimed','quest.completeReward':'Weekly quest · +500 XP','progress.level':'Level {level}',
  'settings.colorTheme':'Color theme','settings.boardStyle':'Board style','theme.lavender':'Lavender','theme.ocean':'Ocean','theme.forest':'Forest','theme.sunset':'Sunset','style.classic':'Classic','style.soft':'Soft','style.paper':'Paper','style.neon':'Neon','toast.unlockLevel':'Unlocks at level {level}',
  'pwa.title':'App & offline','pwa.summaryChecking':'Checking app health…','pwa.summaryReady':'Ready for uninterrupted play','pwa.summaryUpdate':'An update is ready','pwa.connection':'Connection','pwa.online':'Online','pwa.offline':'Offline','pwa.cache':'Offline cache','pwa.ready':'Ready','pwa.unavailable':'Unavailable','pwa.version':'Version','pwa.installation':'Installation','pwa.installed':'Installed','pwa.browser':'In browser','pwa.education':'Install Sudodoku for an app-like experience and reliable offline play.','pwa.install':'Install app','pwa.check':'Check for updates','pwa.repair':'Repair offline data','pwa.updateTitle':'A fresh Sudodoku is ready','pwa.updateText':'Update safely without losing your current puzzle.','pwa.updateNow':'Update now','pwa.dismiss':'Dismiss','pwa.updated':'Sudodoku is up to date','pwa.noUpdate':'You already have the latest version','pwa.repaired':'Offline data refreshed','pwa.repairFailed':'Offline repair could not finish','pwa.installUnavailable':'Use your browser menu to install Sudodoku',
  'academy.eyebrow':'Technique Academy','academy.title':'Train your solving eye','academy.lead':'Twelve interactive lessons built from real Sudoku positions, from first singles to expert patterns.','academy.cardTitle':'Read the grid like an expert','academy.settingsHelp':'Practice 12 real patterns with guided lessons','academy.progress':'{completed} of {total} lessons mastered','academy.lessonNumber':'Lesson {number}','academy.mastered':'mastered','academy.masteredLabel':'Mastered','academy.legendPattern':'Pattern','academy.legendElimination':'Elimination','academy.yourTurn':'Your turn','academy.next':'Next lesson','academy.tryAgain':'Not quite. Recheck the highlighted candidates and try again.','academy.lessonComplete':'Lesson mastered','academy.reward':'+{points} focus points earned','academy.level.foundation':'Foundation','academy.level.intermediate':'Intermediate','academy.level.advanced':'Advanced','academy.level.expert':'Expert',
  'academy.rules.short':'Start here','academy.rules.nav':'Quick rules','academy.rules.eyebrow':'30-second primer','academy.rules.title':'Sudoku rules in 30 seconds','academy.rules.lead':'Fill every empty cell so each unit contains the digits 1–9 exactly once.','academy.rules.goalTitle':'One clear goal','academy.rules.goalText':'Complete the board using digits 1–9. The starting clues never change.','academy.rules.rowTitle':'Every row','academy.rules.rowText':'Use each digit once—never repeat a number in the same row.','academy.rules.columnTitle':'Every column','academy.rules.columnText':'Each column also contains 1–9 exactly once.','academy.rules.boxTitle':'Every 3×3 box','academy.rules.boxText':'The nine smaller boxes follow the same no-repeat rule.','academy.rules.notesTitle':'Notes are possibilities','academy.rules.notesText':'Pencil in candidates when you are unsure. A solved cell keeps only its final digit.','academy.rules.start':'Begin lesson 1',
  'academy.nakedSingle.title':'Naked single','academy.nakedSingle.intro':'A cell has only one legal candidate left. The answer is visible directly in its notes.','academy.nakedSingle.step1':'Scan the row, column, and box around the highlighted cell.','academy.nakedSingle.step2':'Every digit except 6 is already ruled out by one of those units.','academy.nakedSingle.step3':'Place 6—the cell has no other legal candidate.','academy.nakedSingle.question':'Which digit must go in the highlighted cell?','academy.nakedSingle.success':'Exactly. With every other candidate removed, 6 is forced.',
  'academy.hiddenSingle.title':'Hidden single','academy.hiddenSingle.intro':'A digit may have several candidates in a cell, but only one possible home inside a unit.','academy.hiddenSingle.step1':'Focus on row 1 and track every place where 7 could appear.','academy.hiddenSingle.step2':'Other empty cells in the row cannot accept 7 because of their columns or boxes.','academy.hiddenSingle.step3':'R1C8 is the only home left, so it must contain 7.','academy.hiddenSingle.question':'Which digit is hidden in the highlighted cell?','academy.hiddenSingle.success':'Correct. The 7 is hidden among other candidates, but unique in its row.',
  'academy.pointingPair.title':'Pointing candidates','academy.pointingPair.intro':'Every place for one digit inside a box lies on the same row or column. The box points outward.','academy.pointingPair.step1':'In box 9, find every candidate 7; all three sit on row 9.','academy.pointingPair.step2':'Box 9 must place its 7 in one of those highlighted cells.','academy.pointingPair.step3':'Remove 7 from the rest of row 9 outside that box.','academy.pointingPair.question':'Which candidate is pointing out of the box?','academy.pointingPair.success':'Correct. Candidate 7 is locked to row 9 inside the box and disappears elsewhere on that row.',
  'academy.boxLineReduction.title':'Box/line reduction','academy.boxLineReduction.intro':'When every candidate on a line falls inside one box, that line claims the digit for the box.','academy.boxLineReduction.step1':'Scan column 4 and locate every possible 5.','academy.boxLineReduction.step2':'All of them lie inside the middle-left box.','academy.boxLineReduction.step3':'Remove 5 from the other cells of that box.','academy.boxLineReduction.question':'Which candidate is claimed by the line?','academy.boxLineReduction.success':'Exactly. Column 4 claims candidate 5 inside one box, producing six eliminations.',
  'academy.nakedPair.title':'Naked pair','academy.nakedPair.intro':'Two cells in one unit contain the same two candidates. Those digits belong to the pair.','academy.nakedPair.step1':'Find the two highlighted cells that share exactly the same candidates.','academy.nakedPair.step2':'Those cells reserve 1 and 8, even though their order is not known yet.','academy.nakedPair.step3':'Remove 1 and 8 from every other candidate list in that unit.','academy.nakedPair.question':'Which candidates form the locked pair?','academy.nakedPair.success':'That’s it. The shared 1 & 8 pair eliminates both digits elsewhere in the unit.',
  'academy.hiddenPair.title':'Hidden pair','academy.hiddenPair.intro':'Two digits can appear in only the same two cells of a unit, even when other notes hide them.','academy.hiddenPair.step1':'In column 9, track the only cells that can hold 4 and 8.','academy.hiddenPair.step2':'Both digits are confined to the same two highlighted cells.','academy.hiddenPair.step3':'Keep 4 and 8 there and remove every other candidate from those cells.','academy.hiddenPair.question':'Which digits form the hidden pair?','academy.hiddenPair.success':'Correct. The hidden 4 & 8 pair owns those two cells.',
  'academy.nakedTriple.title':'Naked triple','academy.nakedTriple.intro':'Three cells share only three candidates between them, reserving all three digits for the group.','academy.nakedTriple.step1':'Study the three highlighted cells in row 3.','academy.nakedTriple.step2':'Together their candidates are limited to 6, 8, and 9.','academy.nakedTriple.step3':'Remove those digits from every other cell in the row.','academy.nakedTriple.question':'Which three digits form the naked triple?','academy.nakedTriple.success':'Exactly. The 6, 8 & 9 triple reserves three cells and creates an elimination.',
  'academy.hiddenTriple.title':'Hidden triple','academy.hiddenTriple.intro':'Three digits appear only in the same three cells, hidden among extra candidates.','academy.hiddenTriple.step1':'In row 1, map every possible position for 1, 2, and 6.','academy.hiddenTriple.step2':'Those digits are confined to the three highlighted cells.','academy.hiddenTriple.step3':'Remove all other candidates from those three cells.','academy.hiddenTriple.question':'Which digits form the hidden triple?','academy.hiddenTriple.success':'Correct. The hidden 1, 2 & 6 triple strips away the distracting notes.',
  'academy.xWing.title':'X-Wing','academy.xWing.intro':'One candidate appears in exactly two matching columns across two rows, forming a rectangle.','academy.xWing.step1':'Find two rows where candidate 9 appears in the same two columns.','academy.xWing.step2':'The 9s must occupy opposite corners of that four-cell rectangle.','academy.xWing.step3':'Eliminate 9 from every other cell in those two columns.','academy.xWing.question':'Which candidate is locked into the X-Wing?','academy.xWing.success':'Excellent. Candidate 9 is locked into the four corners and can be removed along the columns.',
  'academy.xyWing.title':'XY-Wing','academy.xyWing.intro':'A two-candidate pivot links two pincers. Whichever pivot digit wins, one pincer must contain their shared candidate.','academy.xyWing.step1':'Find the pivot with candidates 1 and 4, then its 1/3 and 4/3 pincers.','academy.xyWing.step2':'If the pivot is 1, one pincer is 3; if it is 4, the other pincer is 3.','academy.xyWing.step3':'Remove 3 from every cell that sees both pincers.','academy.xyWing.question':'Which candidate can both pincers eliminate?','academy.xyWing.success':'Excellent. Candidate 3 is guaranteed in one pincer and disappears from their shared peers.',
  'academy.skyscraper.title':'Skyscraper','academy.skyscraper.intro':'Two strong links share one base line but have offset roofs, forming a tilted tower.','academy.skyscraper.step1':'Find the two columns where candidate 3 has exactly two positions.','academy.skyscraper.step2':'Their lower ends align while the two roof cells do not.','academy.skyscraper.step3':'Any cell seeing both roofs cannot contain 3.','academy.skyscraper.question':'Which candidate builds the Skyscraper?','academy.skyscraper.success':'Correct. One roof must be 3, so their common peers lose candidate 3.',
  'academy.swordfish.title':'Swordfish','academy.swordfish.intro':'A candidate in three lines is confined to the same three crossing lines—the three-line cousin of X-Wing.','academy.swordfish.step1':'Trace candidate 9 across the three highlighted base lines.','academy.swordfish.step2':'Every possible 9 lands within only three crossing lines.','academy.swordfish.step3':'Remove 9 from those crossing lines outside the fish.','academy.swordfish.question':'Which candidate is trapped in the Swordfish?','academy.swordfish.success':'Masterful. The three-line Swordfish confines candidate 9 and produces a safe elimination.',
  'backup.title':'Backup & transfer','backup.help':'Export one portable file, then restore it from Sudodoku on another device. Nothing is uploaded.','backup.summary':'{played} games · {achievements} achievements','backup.export':'Export backup','backup.exportHelp':'Save progress and settings','backup.restore':'Restore backup','backup.restoreHelp':'Choose a Sudodoku file','backup.private':'Backups stay readable and entirely under your control.','backup.lastExport':'Last export: {date}','backup.exported':'Portable backup created','backup.reading':'Checking backup integrity…','backup.confirm':'Restore this backup? Current progress and settings on this device will be replaced.','backup.cancelled':'Restore cancelled—nothing changed.','backup.restored':'Backup restored—reloading Sudodoku…','backup.invalid':'This file is not a valid or intact Sudodoku backup.',
  'replay.watch':'Watch replay','replay.timeline':'Solve timeline','replay.title':'Your journey','replay.play':'Play replay','replay.pause':'Pause replay','replay.start':'Starting grid','replay.value':'Placed {value}','replay.erase':'Erased a cell','replay.hint':'Hint placed {value}','replay.snapshot':'Undo','share.cardTitle':'Puzzle complete','share.cardFooter':'Made especially for Edmundas · Sudodoku',
};

const lt = {
  'languageLaunch.eyebrow':'Sveiki · Welcome · Bienvenido','languageLaunch.title':'Pasirink savo kalbą','languageLaunch.lead':'Pasirink kalbą, kurią „Sudodoku“ įsimins šiame įrenginyje.','languageLaunch.selected':'Pasirinkta: {language}','languageLaunch.continue':'Tęsti','languageLaunch.changeAnytime':'Kalbą bet kada galėsi pakeisti Nuostatose.',
  'intro.eyebrow':'Ramesnis galvosūkis','intro.title':'Mąstyk aiškiai.<br><em>Žaisk gražiai.</em>','intro.lead':'Aukščiausios kokybės Sudoku patirtis su apgalvotomis užuominomis, kasdieniais iššūkiais ir įrenginyje saugoma pažanga.','intro.featureOffline':'Veikia be interneto','intro.featureOfflineText':'Žaisk bet kur po pirmojo apsilankymo.','intro.featureCoach':'Švelnios užuominos','intro.featureCoachText':'Aiškios užuominos padeda rasti kitą žingsnį.','intro.featureProgress':'Asmeninė pažanga','intro.featureProgressText':'Augink serijas ir atrakink pasiekimus.','intro.start':'Pradėti pirmą galvosūkį','intro.note':'Kalba ir nuostatos šiame įrenginyje išsaugomos visam laikui.','intro.daily':'Dienos iššūkis','intro.ready':'Laukia tavęs',
  'dedication.label':'Asmeninė dedikacija','dedication.madeFor':'Sukurta specialiai Edmundui','dedication.message':'Rami vieta logikai, susikaupimui ir gražiam mąstymui – sukurta su rūpesčiu.','dedication.footer':'Sukurta Edmundui ir susikaupimo akimirkoms.','dedication.short':'Edmundui',
  'mainMenu.personal':'Tavo Sudoku erdvė','mainMenu.welcome':'Smagu, kad sugrįžai.<br><em>Atrask savo ritmą.</em>','mainMenu.lead':'Tavo rami vieta logikai, susikaupimui ir skaidriam mąstymui.','mainMenu.continue':'Tęsti galvosūkį','mainMenu.startFresh':'Pradėti naują galvosūkį','mainMenu.progress':'Įveikta {percent}%','mainMenu.ready':'Galima pradėti','mainMenu.newPuzzle':'Naujas galvosūkis','mainMenu.choose':'Pasirink kitą ritmą','mainMenu.dailyHelp':'Bendras šiandienos iššūkis','mainMenu.yourJourney':'Tavo kelionė','mainMenu.forEdmundas':'Sukurta Edmundui','mainMenu.statsHelp':'Peržiūrėti serijas ir pasiekimus','mainMenu.settingsHelp':'Temos, kopijos ir kalba','mainMenu.open':'Eiti į pagrindinį meniu',
  'settings.personalize':'Pritaikyk sau','settings.title':'Nuostatos','settings.language':'Kalba','settings.languageHelp':'Visam laikui išsaugoma šiame įrenginyje','settings.haptics':'Vibracijos atsakas','settings.hapticsHelp':'Švelni vibracija palaikomuose telefonuose','settings.autoPause':'Automatinė pauzė','settings.autoPauseHelp':'Pristabdyti, kai „Sudodoku“ veikia fone','settings.replayIntro':'Pakartoti pristatymą',
  'game.currentPuzzle':'Dabartinis galvosūkis','game.mistakes':'Klaidos','game.paused':'Žaidimas pristabdytas','game.resume':'Paliesk ir tęsk','game.newGame':'Naujas žaidimas','game.progress':'Galvosūkio pažanga','game.progressText':'{count} iš 81 langelio','mode.classic':'Klasikinis','mode.daily':'Dienos',
  'tools.undo':'Atšaukti','tools.erase':'Ištrinti','tools.notes':'Pastabos','tools.smartNotes':'Išmanios pastabos','tools.hint':'Užuomina','tools.on':'Įj.','tools.off':'Išj.',
  'difficulty.easy':'Lengvas','difficulty.easyMood':'Ramus','difficulty.medium':'Vidutinis','difficulty.mediumMood':'Subalansuotas','difficulty.hard':'Sunkus','difficulty.hardMood':'Susikaupęs','difficulty.expert':'Ekspertas','difficulty.expertMood':'Bebaimis',
  'daily.practice':'Kasdienė praktika','daily.headline':'Atrask savo<br><em>ritmą.</em>','daily.tagline':'Nutildyk triukšmą. Po vieną skaičių.','daily.quote':'Logika nuves nuo A iki B. Vaizduotė nuves visur.','daily.today':'Šiandienos iššūkis','daily.complete':'Dienos užduotis įveikta','daily.play':'Žaisti dabar','daily.replay':'Kartoti','daily.streak':'{count} dienos serija','daily.streakPlural':'{count} dienų serija',
  'hint.title':'{row} eilutė, {column} stulpelis yra {value}','hint.text':'Auksinis langelis atskleistas. Peržvelk jo eilutę, stulpelį ir 3×3 bloką.','hint.revealed':'Užuomina atskleista','hint.look':'Žiūrėk į paryškintą langelį.',
  'footer.focus':'Sukurta susikaupimo akimirkoms.','footer.offline':'Veikia be interneto',
  'result.time':'Laikas','result.score':'Susikaupimo taškai','result.unlocked':'Atrakintas pasiekimas','result.playAnother':'Žaisti dar kartą','result.share':'Dalintis rezultatu','result.complete':'Galvosūkis įveiktas','result.dailyComplete':'Dienos iššūkis įveiktas','result.flawless':'Tobulas susikaupimas.','result.beautiful':'Puikiai padirbėta.','result.dailyText':'Šiandienos tinklelis užbaigtas. Tavo kasdienis ritmas stiprėja.','result.completeText':'Atradai ritmą ir užbaigei galvosūkį.','result.gameOver':'Žaidimas baigtas','result.almost':'Beveik pavyko.','result.failedText':'Trys maži suklydimai. Atsikvėpk ir pradėk iš naujo.',
  'stats.practice':'Tavo praktika','stats.title':'Statistika','stats.played':'Žaista','stats.winRate':'Pergalių dalis','stats.streak':'Serija','stats.best':'Geriausias laikas','stats.points':'Susikaupimo taškai','stats.daily':'Dienos pergalės','stats.achievements':'Pasiekimai','stats.keepPlaying':'Tęsti žaidimą',
  'achievement.first-flow':'Pirmasis ritmas','achievement.clean-grid':'Tobulas sprendimas','achievement.pure-logic':'Gryna logika','achievement.speed-focus':'Mažiau nei 5 min.','achievement.daily-devotion':'Kasdienė ištikimybė','achievement.streak-three':'3 dienų serija','achievement.expert-mind':'Eksperto protas','achievement.new':'Naujas pasiekimas',
  'achievement.first-flow.desc':'Užbaik pirmąjį galvosūkį.','achievement.clean-grid.desc':'Užbaik galvosūkį be klaidų.','achievement.pure-logic.desc':'Laimėk be užuominų ir išmaniųjų pastabų.','achievement.speed-focus.desc':'Užbaik bet kurį žaidimą greičiau nei per 5 minutes.','achievement.daily-devotion.desc':'Užbaik pirmąjį Dienos iššūkį.','achievement.streak-three.desc':'Pasiek 3 dienų Dienos seriją.','achievement.expert-mind.desc':'Užbaik Eksperto galvosūkį.',
  'achievement.explorer':'Visas žemėlapis','achievement.explorer.desc':'Laimėk po kartą Killer, Hyper ir Mini režimuose.','achievement.mini-sprint':'Kišeninis žaibas','achievement.mini-sprint.desc':'Užbaik Mini 6×6 greičiau nei per 90 sekundžių.','achievement.perfect-ten':'Nesudrebinamas','achievement.perfect-ten.desc':'Užbaik 10 galvosūkių iš eilės be klaidų.',
  'achievement.academy-initiate':'Raštų mokinys','achievement.academy-initiate.desc':'Įvaldyk 4 Technikų akademijos pamokas.','achievement.academy-scholar':'Akademijos žinovas','achievement.academy-scholar.desc':'Įvaldyk 8 Technikų akademijos pamokas.','achievement.fish-school':'Žuvų stebėtojas','achievement.fish-school.desc':'Įvaldyk X-Wing ir Swordfish technikas.','achievement.academy-master':'Akademijos meistras','achievement.academy-master.desc':'Įvaldyk visas Technikų akademijos pamokas.','achievement.pattern-voyager':'Raštų keliautojas','achievement.pattern-voyager.desc':'Atrask 6 skirtingas sprendimo technikas.','achievement.logical-guide':'Logikos vedlys','achievement.logical-guide.desc':'Panaudok 100 technikas paaiškinančių užuominų.','achievement.technique-librarian':'Technikų bibliotekininkas','achievement.technique-librarian.desc':'Atrask visas Akademijos technikas.','achievement.deduction-sage':'Dedukcijos išminčius','achievement.deduction-sage.desc':'Panaudok 1 000 technikas paaiškinančių užuominų – tai tikras ilgalaikis žygdarbis.',
  'achievement.killer-adept':'Narvelių tramdytojas','achievement.killer-adept.desc':'Užbaik 25 Killer galvosūkius.','achievement.hyper-architect':'Hyper architektas','achievement.hyper-architect.desc':'Užbaik 25 Hyper galvosūkius.','achievement.zen-master':'Ramus vanduo','achievement.zen-master.desc':'Užbaik 50 Zen galvosūkių.','achievement.variant-voyager':'Variantų keliautojas','achievement.variant-voyager.desc':'Užbaik 100 variantų galvosūkių.','achievement.logic-fifty':'Grynas protas','achievement.logic-fifty.desc':'Laimėk 50 kartų be užuominų ir išmaniųjų pastabų.','achievement.expert-pure':'Be apsaugos','achievement.expert-pure.desc':'Laimėk 50 Eksperto žaidimų be pagalbos.','achievement.weekly-ten':'Užduočių sergėtojas','achievement.weekly-ten.desc':'Įvykdyk 10 Savaitės užduočių.','achievement.daily-thirty':'Mėnesio ritualas','achievement.daily-thirty.desc':'Pasiek 30 dienų Dienos seriją.','achievement.century':'Šimtuko klubas','achievement.century.desc':'Užbaik 100 galvosūkių.',
  'achievement.perfect-century':'Deimantinis tikslumas','achievement.perfect-century.desc':'Užbaik 100 galvosūkių be klaidų.','achievement.logic-legend':'Logikos legenda','achievement.logic-legend.desc':'Laimėk 250 kartų be pagalbos.','achievement.weekly-fifty':'Nepailstantis tyrinėtojas','achievement.weekly-fifty.desc':'Įvykdyk 50 Savaitės užduočių.','achievement.level-twenty-five':'Susikaupimo viršūnė','achievement.level-twenty-five.desc':'Pasiek 25 pažangos lygį.','achievement.deep-focus':'Gilus susikaupimas','achievement.deep-focus.desc':'Praleisk 100 valandų spręsdamas užbaigtus galvosūkius.','achievement.daily-century':'Šimtas rytų','achievement.daily-century.desc':'Pasiek 100 dienų Dienos seriją.','achievement.year-of-focus':'Susikaupimo metai','achievement.year-of-focus.desc':'Išlaikyk 365 dienų Dienos seriją.','achievement.grandmaster':'Sudodoku didmeistris','achievement.grandmaster.desc':'Užbaik 1 000 galvosūkių.','achievement.level-fifty':'Aukščiau meistriškumo','achievement.level-fifty.desc':'Pasiek 50 pažangos lygį.',
  'achievement.night-owl':'Mėnulio protas','achievement.night-owl.desc':'Užbaik galvosūkį tarp vidurnakčio ir 5 valandos ryto.','achievement.close-call':'Ant ribos','achievement.close-call.desc':'Laimėk padaręs lygiai dvi klaidas.','achievement.no-pencil':'Be pėdsako','achievement.no-pencil.desc':'Užbaik Sunkų arba Eksperto galvosūkį be užuominų ir jokių pastabų.','achievement.patient-mind':'Kantrus protas','achievement.patient-mind.desc':'Spręsk bent 45 minutes ir užbaik be užuominos.',
  'achievement.tier.common':'Dažnas','achievement.tier.rare':'Retas','achievement.tier.epic':'Epinis','achievement.tier.legendary':'Legendinis','achievement.tier.mythic':'Mitinis','achievement.tier.secret':'Slaptas','achievement.completed':'Įvykdyta','achievement.hours':'val.','achievement.multiple':'Atrakinta pasiekimų: {count}','achievement.secret':'Slaptas pasiekimas','achievement.secret.desc':'Sąlyga lieka paslėpta, kol pasiekimas atrakinamas.','achievement.hidden':'Paslėpta','achievement.history':'Pasiekimų istorija','achievement.historyEmpty':'Būsimi tavo pasiekimai atsiras čia.','achievement.unlockedEvent':'Atrakintas pasiekimas','achievement.almostThere':'Tikslas jau arti','achievement.styleUnlocked':'Atrakintas naujas stilius','achievement.progressEvent':'Įvykdyta {current} iš {target}','achievement.historyCount':'Gauta: {count}',
  'toast.restored':'Žaidimas atkurtas — galima tęsti','toast.creating':'Kuriamas naujas galvosūkis…','toast.dailyReady':'Šiandienos iššūkis paruoštas','toast.puzzleReady':'Paruoštas: {difficulty}','toast.smartNotes':'Pažymėti {count} galimi skaičiai','toast.smartNotesOn':'Išmanios pastabos įjungtos · kandidatų: {count}','toast.smartNotesOff':'Išmanios pastabos išjungtos · kandidatai pašalinti','toast.shared':'Rezultatu pasidalinta','toast.copied':'Rezultatas nukopijuotas','toast.cardSaved':'Rezultato kortelė išsaugota','toast.offlineLater':'Režimas be interneto veiks kitą kartą','toast.languageSaved':'Kalba išsaugota visam laikui',
  'share.text':'Sudodoku {difficulty} · {time} · klaidos: {mistakes} · susikaupimo taškai: {score}','share.title':'Mano „Sudodoku“ rezultatas',
  'common.notNow':'Ne dabar','common.done':'Atlikta','common.settings':'Nuostatos','common.statistics':'Statistika','common.sound':'Garsas','common.theme':'Tema','common.pause':'Pristabdyti žaidimą','common.language':'Kalba',
  'game.progressOf':'{count} iš {total} langelių','mode.classicHelp':'Nesenstantis 9×9 žaidimas','mode.killer':'Killer','mode.killerHelp':'Narveliai ir sumos','mode.hyper':'Hyper','mode.hyperHelp':'Keturi papildomi regionai','mode.mini':'Mini 6×6','mode.miniHelp':'Trumpas susikaupimas','mode.zen':'Zen','mode.zenHelp':'Be laiko ir klaidų',
  'unit.row':'{number} eilutėje','unit.column':'{number} stulpelyje','unit.box':'{number} bloke','unit.hyper':'{number} hyper regione',
  'technique.nakedSingle.title':'Vienintelis kandidatas · R{row}C{column} = {value}','technique.nakedSingle.text':'Šiame langelyje gali būti tik {value}. Visus kitus kandidatus atmeta eilutė, stulpelis arba blokas.','technique.hiddenSingle.title':'Paslėptas vienintelis · {value}','technique.hiddenSingle.text':'{unitLabel} skaičius {value} gali būti tik langelyje {cellsLabel}.','technique.nakedPair.title':'Atvira pora · {pairLabel}','technique.nakedPair.text':'{cellsLabel} rezervuoja {pairLabel} – šiuos kandidatus galima pašalinti iš {targetsLabel}.','technique.pointingPair.title':'Nukreipti kandidatai · {value}','technique.pointingPair.text':'{unitLabel} visi {value} kandidatai yra vienoje linijoje, todėl {value} pašalinamas iš {targetsLabel} už bloko ribų.','technique.boxLineReduction.title':'Bloko ir linijos sąveika · {value}','technique.boxLineReduction.text':'Visi šios linijos {value} kandidatai yra viename bloke, todėl {value} pašalinamas iš {targetsLabel} kitose bloko vietose.','technique.hiddenPair.title':'Paslėpta pora · {pairLabel}','technique.hiddenPair.text':'{unitLabel} tik {cellsLabel} gali turėti {pairLabel}, todėl kiti jų kandidatai pašalinami.','technique.nakedTriple.title':'Atviras trejetas · {valuesLabel}','technique.nakedTriple.text':'Trys langeliai {unitLabel} rezervuoja {valuesLabel}, todėl šie skaičiai pašalinami iš {targetsLabel}.','technique.hiddenTriple.title':'Paslėptas trejetas · {valuesLabel}','technique.hiddenTriple.text':'{unitLabel} tik trys langeliai gali turėti {valuesLabel}, todėl pašalinami kiti jų kandidatai.','technique.xWing.title':'X-Wing · kandidatas {value}','technique.xWing.text':'Keturi kampai {cellsLabel} užfiksuoja {value}, todėl jis pašalinamas iš {targetsLabel}.','technique.xyWing.title':'XY-Wing · pašalink {value}','technique.xyWing.text':'Ašinis langelis ir dvi žnyplės ties {cellsLabel} garantuoja {value} vienoje žnyplėje, todėl jis pašalinamas iš {targetsLabel}.','technique.skyscraper.title':'Dangoraižis · kandidatas {value}','technique.skyscraper.text':'Dvi paslinktos stiprios jungtys linijose {linesLabel} garantuoja {value} viename stoge, todėl jis pašalinamas iš {targetsLabel}.','technique.swordfish.title':'Swordfish · kandidatas {value}','technique.swordfish.text':'Trys linijos apriboja {value} trimis kertančiomis linijomis, todėl jis pašalinamas iš {targetsLabel}.','technique.reveal.title':'Atskleidimas · R{row}C{column} = {value}','technique.reveal.text':'Šiuo metu nerasta palaikomo loginio rašto, todėl atskleidžiamas šis langelis.',
  'quest.weekly':'Savaitės užduotis','quest.complete.title':'Ritmo būsena','quest.complete.text':'Šią savaitę užbaik {target} galvosūkius','quest.logic.title':'Gryna logika','quest.logic.text':'Laimėk {target} kartus be užuominų','quest.variants.title':'Tyrinėtojas','quest.variants.text':'Užbaik {target} variantų žaidimus','quest.daily.title':'Kasdienis ritmas','quest.daily.text':'Užbaik {target} dienos iššūkius','quest.claimed':'Gauta','quest.completeReward':'Savaitės užduotis · +500 XP','progress.level':'{level} lygis',
  'settings.colorTheme':'Spalvų tema','settings.boardStyle':'Lentos stilius','theme.lavender':'Levandų','theme.ocean':'Vandenyno','theme.forest':'Miško','theme.sunset':'Saulėlydžio','style.classic':'Klasikinis','style.soft':'Švelnus','style.paper':'Popierius','style.neon':'Neonas','toast.unlockLevel':'Atsirakina {level} lygyje',
  'pwa.title':'Programėlė ir ryšys','pwa.summaryChecking':'Tikrinama programėlės būsena…','pwa.summaryReady':'Paruošta nepertraukiamam žaidimui','pwa.summaryUpdate':'Paruoštas atnaujinimas','pwa.connection':'Ryšys','pwa.online':'Prisijungta','pwa.offline':'Be interneto','pwa.cache':'Duomenys be ryšio','pwa.ready':'Paruošta','pwa.unavailable':'Nepasiekiama','pwa.version':'Versija','pwa.installation':'Įdiegimas','pwa.installed':'Įdiegta','pwa.browser':'Naršyklėje','pwa.education':'Įdiek „Sudodoku“ kaip programėlę ir patikimai žaisk be interneto.','pwa.install':'Įdiegti','pwa.check':'Tikrinti naujinius','pwa.repair':'Atkurti duomenis','pwa.updateTitle':'Paruošta nauja „Sudodoku“ versija','pwa.updateText':'Atnaujink saugiai – dabartinis galvosūkis nedings.','pwa.updateNow':'Atnaujinti','pwa.dismiss':'Uždaryti','pwa.updated':'„Sudodoku“ atnaujinta','pwa.noUpdate':'Jau naudoji naujausią versiją','pwa.repaired':'Duomenys be interneto atnaujinti','pwa.repairFailed':'Nepavyko atkurti duomenų','pwa.installUnavailable':'Įdiek „Sudodoku“ per naršyklės meniu',
  'academy.eyebrow':'Technikų akademija','academy.title':'Lavink sprendėjo žvilgsnį','academy.lead':'Dvylika interaktyvių pamokų iš tikrų Sudoku situacijų – nuo pirmųjų vienetų iki ekspertinių raštų.','academy.cardTitle':'Skaityk tinklelį kaip ekspertas','academy.settingsHelp':'Mokykis 12 tikrų raštų su vedamomis pamokomis','academy.progress':'Įveikta {completed} iš {total} pamokų','academy.lessonNumber':'{number} pamoka','academy.mastered':'įvaldyta','academy.masteredLabel':'Įvaldyta','academy.legendPattern':'Raštas','academy.legendElimination':'Atmetimas','academy.yourTurn':'Tavo eilė','academy.next':'Kita pamoka','academy.tryAgain':'Dar ne. Peržvelk paryškintus kandidatus ir bandyk dar kartą.','academy.lessonComplete':'Pamoka įvaldyta','academy.reward':'Gauta susikaupimo taškų: {points}','academy.level.foundation':'Pagrindai','academy.level.intermediate':'Vidutinis','academy.level.advanced':'Pažengęs','academy.level.expert':'Ekspertinis',
  'academy.rules.short':'Pradėk čia','academy.rules.nav':'Trumpos taisyklės','academy.rules.eyebrow':'30 sekundžių įvadas','academy.rules.title':'Sudoku taisyklės per 30 sekundžių','academy.rules.lead':'Užpildyk tuščius langelius taip, kad kiekvienoje srityje skaičiai 1–9 būtų panaudoti po vieną kartą.','academy.rules.goalTitle':'Vienas aiškus tikslas','academy.rules.goalText':'Užpildyk lentą skaičiais 1–9. Pradiniai skaičiai niekada nekeičiami.','academy.rules.rowTitle':'Kiekviena eilutė','academy.rules.rowText':'Kiekvieną skaičių naudok vieną kartą – eilutėje negali būti pasikartojimų.','academy.rules.columnTitle':'Kiekvienas stulpelis','academy.rules.columnText':'Kiekviename stulpelyje skaičiai 1–9 taip pat naudojami po vieną kartą.','academy.rules.boxTitle':'Kiekvienas 3×3 blokas','academy.rules.boxText':'Devyni mažesni blokai laikosi tos pačios taisyklės be pasikartojimų.','academy.rules.notesTitle':'Pastabos žymi galimybes','academy.rules.notesText':'Kai nesi tikras, pasižymėk kandidatus. Išspręstame langelyje lieka tik galutinis skaičius.','academy.rules.start':'Pradėti 1 pamoką',
  'academy.nakedSingle.title':'Vienintelis kandidatas','academy.nakedSingle.intro':'Langelyje liko tik vienas galimas kandidatas. Atsakymas tiesiogiai matomas pastabose.','academy.nakedSingle.step1':'Peržvelk paryškinto langelio eilutę, stulpelį ir bloką.','academy.nakedSingle.step2':'Visus skaičius, išskyrus 6, jau atmeta viena iš šių sričių.','academy.nakedSingle.step3':'Įrašyk 6 – jokio kito teisėto kandidato nėra.','academy.nakedSingle.question':'Kuris skaičius turi būti paryškintame langelyje?','academy.nakedSingle.success':'Teisingai. Atmetus visus kitus kandidatus, 6 yra privalomas.',
  'academy.hiddenSingle.title':'Paslėptas vienintelis','academy.hiddenSingle.intro':'Langelyje gali būti keli kandidatai, tačiau srityje skaičiui gali likti tik viena vieta.','academy.hiddenSingle.step1':'Sutelk dėmesį į 1 eilutę ir rask visas vietas, kur galėtų būti 7.','academy.hiddenSingle.step2':'Kiti tušti eilutės langeliai negali priimti 7 dėl savo stulpelių ar blokų.','academy.hiddenSingle.step3':'R1C8 yra vienintelė likusi vieta, todėl joje turi būti 7.','academy.hiddenSingle.question':'Kuris skaičius paslėptas paryškintame langelyje?','academy.hiddenSingle.success':'Teisingai. 7 slepiasi tarp kitų kandidatų, bet eilutėje yra vienintelis.',
  'academy.pointingPair.title':'Nukreipti kandidatai','academy.pointingPair.intro':'Kai visos vieno skaičiaus vietos bloke yra toje pačioje eilutėje ar stulpelyje, blokas rodo į išorę.','academy.pointingPair.step1':'9 bloke rask visus kandidatus 7 – visi trys yra 9 eilutėje.','academy.pointingPair.step2':'9 blokas privalo įrašyti 7 viename iš šių paryškintų langelių.','academy.pointingPair.step3':'Pašalink 7 iš likusios 9 eilutės už šio bloko.','academy.pointingPair.question':'Kuris kandidatas nukreiptas iš bloko?','academy.pointingPair.success':'Teisingai. Kandidatas 7 užrakintas 9 eilutėje bloko viduje ir pašalinamas kitur eilutėje.',
  'academy.boxLineReduction.title':'Bloko ir linijos sąveika','academy.boxLineReduction.intro':'Kai visi linijos kandidatai yra viename bloke, linija rezervuoja tą skaičių bloke.','academy.boxLineReduction.step1':'Peržvelk 4 stulpelį ir rask visas galimas 5 vietas.','academy.boxLineReduction.step2':'Visos jos yra viduriniame kairiajame bloke.','academy.boxLineReduction.step3':'Pašalink 5 iš kitų to bloko langelių.','academy.boxLineReduction.question':'Kurį kandidatą rezervuoja linija?','academy.boxLineReduction.success':'Tiksliai. 4 stulpelis rezervuoja 5 viename bloke ir leidžia atlikti šešis pašalinimus.',
  'academy.nakedPair.title':'Atvira pora','academy.nakedPair.intro':'Du vienos srities langeliai turi tuos pačius du kandidatus. Šie skaičiai priklauso porai.','academy.nakedPair.step1':'Rask du paryškintus langelius su visiškai vienodais kandidatais.','academy.nakedPair.step2':'Šie langeliai rezervuoja 1 ir 8, nors jų tvarka dar nežinoma.','academy.nakedPair.step3':'Pašalink 1 ir 8 iš visų kitų tos srities kandidatų sąrašų.','academy.nakedPair.question':'Kurie kandidatai sudaro užrakintą porą?','academy.nakedPair.success':'Puiku. Bendra 1 ir 8 pora pašalina abu skaičius kitose srities vietose.',
  'academy.hiddenPair.title':'Paslėpta pora','academy.hiddenPair.intro':'Du skaičiai gali būti tik tuose pačiuose dviejuose srities langeliuose, net jei juos slepia kitos pastabos.','academy.hiddenPair.step1':'9 stulpelyje rask vienintelius langelius, galinčius turėti 4 ir 8.','academy.hiddenPair.step2':'Abu skaičiai apriboti tais pačiais dviem paryškintais langeliais.','academy.hiddenPair.step3':'Palik juose 4 ir 8, o kitus kandidatus pašalink.','academy.hiddenPair.question':'Kurie skaičiai sudaro paslėptą porą?','academy.hiddenPair.success':'Teisingai. Paslėpta 4 ir 8 pora valdo šiuos du langelius.',
  'academy.nakedTriple.title':'Atviras trejetas','academy.nakedTriple.intro':'Trys langeliai kartu turi tik tris kandidatus ir rezervuoja visus tris skaičius.','academy.nakedTriple.step1':'Išnagrinėk tris paryškintus 3 eilutės langelius.','academy.nakedTriple.step2':'Jų bendri kandidatai apsiriboja 6, 8 ir 9.','academy.nakedTriple.step3':'Pašalink šiuos skaičius iš kitų eilutės langelių.','academy.nakedTriple.question':'Kurie trys skaičiai sudaro atvirą trejetą?','academy.nakedTriple.success':'Tiksliai. 6, 8 ir 9 rezervuoja tris langelius ir leidžia pašalinti kandidatą.',
  'academy.hiddenTriple.title':'Paslėptas trejetas','academy.hiddenTriple.intro':'Trys skaičiai gali būti tik tuose pačiuose trijuose langeliuose, paslėpti tarp papildomų kandidatų.','academy.hiddenTriple.step1':'1 eilutėje pažymėk visas galimas 1, 2 ir 6 vietas.','academy.hiddenTriple.step2':'Šie skaičiai apriboti trimis paryškintais langeliais.','academy.hiddenTriple.step3':'Pašalink visus kitus kandidatus iš šių langelių.','academy.hiddenTriple.question':'Kurie skaičiai sudaro paslėptą trejetą?','academy.hiddenTriple.success':'Teisingai. Paslėptas 1, 2 ir 6 trejetas pašalina klaidinančias pastabas.',
  'academy.xWing.title':'X-Wing','academy.xWing.intro':'Vienas kandidatas dviejose eilutėse pasirodo tik tuose pačiuose dviejuose stulpeliuose ir sudaro stačiakampį.','academy.xWing.step1':'Rask dvi eilutes, kuriose kandidatas 9 yra tuose pačiuose dviejuose stulpeliuose.','academy.xWing.step2':'Devynetai turi užimti priešingus keturių langelių stačiakampio kampus.','academy.xWing.step3':'Pašalink 9 iš visų kitų tų dviejų stulpelių langelių.','academy.xWing.question':'Kuris kandidatas užrakintas X-Wing rašte?','academy.xWing.success':'Puikiai. Kandidatas 9 užrakintas keturiuose kampuose ir pašalinamas iš kitų stulpelių vietų.',
  'academy.xyWing.title':'XY-Wing','academy.xyWing.intro':'Dviejų kandidatų ašis sujungia dvi žnyples. Kad ir kuris ašies skaičius laimėtų, viena žnyplė turės bendrą kandidatą.','academy.xyWing.step1':'Rask ašį su 1 ir 4, tada jos 1/3 ir 4/3 žnyples.','academy.xyWing.step2':'Jei ašis yra 1, viena žnyplė tampa 3; jei 4 – kita tampa 3.','academy.xyWing.step3':'Pašalink 3 iš visų langelių, matančių abi žnyples.','academy.xyWing.question':'Kurį kandidatą gali pašalinti abi žnyplės?','academy.xyWing.success':'Puikiai. Vienoje žnyplėje 3 yra garantuotas, todėl jis dingsta iš bendrų kaimynų.',
  'academy.skyscraper.title':'Dangoraižis','academy.skyscraper.intro':'Dvi stiprios jungtys turi bendrą pagrindo liniją, bet paslinktus stogus – susidaro pakrypęs bokštas.','academy.skyscraper.step1':'Rask du stulpelius, kuriuose kandidatas 3 turi tik dvi vietas.','academy.skyscraper.step2':'Jų apatiniai galai sutampa, o stogo langeliai – ne.','academy.skyscraper.step3':'Joks langelis, matantis abu stogus, negali turėti 3.','academy.skyscraper.question':'Kuris kandidatas stato Dangoraižį?','academy.skyscraper.success':'Teisingai. Vienas stogas privalo būti 3, todėl bendri kaimynai praranda kandidatą 3.',
  'academy.swordfish.title':'Swordfish','academy.swordfish.intro':'Trijose linijose kandidatas apribotas tomis pačiomis trimis kertančiomis linijomis – tai trijų linijų X-Wing giminaitis.','academy.swordfish.step1':'Sek kandidatą 9 trijose paryškintose pagrindo linijose.','academy.swordfish.step2':'Visos galimos 9 vietos telpa tik trijose kertančiose linijose.','academy.swordfish.step3':'Pašalink 9 iš tų linijų už rašto ribų.','academy.swordfish.question':'Kuris kandidatas įstrigęs Swordfish rašte?','academy.swordfish.success':'Meistriška. Trijų linijų Swordfish apriboja kandidatą 9 ir leidžia saugiai jį pašalinti.',
  'backup.title':'Atsarginė kopija ir perkėlimas','backup.help':'Eksportuok vieną failą ir atkurk jį „Sudodoku“ kitame įrenginyje. Niekas nesiunčiama į internetą.','backup.summary':'Žaidimų: {played} · pasiekimų: {achievements}','backup.export':'Eksportuoti kopiją','backup.exportHelp':'Išsaugoti pažangą ir nuostatas','backup.restore':'Atkurti kopiją','backup.restoreHelp':'Pasirinkti „Sudodoku“ failą','backup.private':'Kopija lieka skaitoma ir visiškai tavo valdoma.','backup.lastExport':'Paskutinė kopija: {date}','backup.exported':'Perkeliama kopija sukurta','backup.reading':'Tikrinamas kopijos vientisumas…','backup.confirm':'Atkurti šią kopiją? Dabartinė šio įrenginio pažanga ir nuostatos bus pakeistos.','backup.cancelled':'Atkūrimas atšauktas – niekas nepakeista.','backup.restored':'Kopija atkurta – „Sudodoku“ paleidžiama iš naujo…','backup.invalid':'Tai nėra tinkama arba nepažeista „Sudodoku“ kopija.',
  'replay.watch':'Žiūrėti pakartojimą','replay.timeline':'Sprendimo eiga','replay.title':'Tavo kelionė','replay.play':'Leisti pakartojimą','replay.pause':'Pristabdyti pakartojimą','replay.start':'Pradinis tinklelis','replay.value':'Įrašyta {value}','replay.erase':'Ištrintas langelis','replay.hint':'Užuomina įrašė {value}','replay.snapshot':'Atšaukimas','share.cardTitle':'Galvosūkis įveiktas','share.cardFooter':'Sukurta specialiai Edmundui · Sudodoku',
};

const es = {
  ...en,
  'languageLaunch.eyebrow':'Bienvenido · Sveiki · Welcome','languageLaunch.title':'Elige tu idioma','languageLaunch.lead':'Elige el idioma que Sudodoku recordará en este dispositivo.','languageLaunch.selected':'Seleccionado: {language}','languageLaunch.continue':'Continuar','languageLaunch.changeAnytime':'Puedes cambiarlo cuando quieras en Ajustes.',
  'mainMenu.personal':'Tu espacio Sudoku','mainMenu.welcome':'Qué bueno verte de nuevo.<br><em>Encuentra tu ritmo.</em>',
  'intro.eyebrow':'Un rompecabezas más sereno','intro.title':'Piensa con claridad.<br><em>Juega con estilo.</em>','intro.lead':'Una experiencia Sudoku premium con pistas útiles, retos diarios y progreso guardado en tu dispositivo.','intro.featureOffline':'Realmente sin conexión','intro.featureOfflineText':'Juega donde quieras después de tu primera visita.','intro.featureCoach':'Ayuda amable','intro.featureCoachText':'Las pistas visibles te ayudan con el siguiente paso.','intro.featureProgress':'Progreso personal','intro.featureProgressText':'Crea rachas y desbloquea logros.','intro.start':'Comenzar mi primer puzzle','intro.note':'Tu idioma y preferencias se guardan permanentemente en este dispositivo.','settings.personalize':'Hazlo tuyo','settings.title':'Ajustes','settings.language':'Idioma','settings.languageHelp':'Guardado permanentemente en este dispositivo','settings.haptics':'Respuesta háptica','settings.autoPause':'Pausa automática','settings.replayIntro':'Repetir introducción','game.currentPuzzle':'Puzzle actual','game.mistakes':'Errores','game.paused':'Juego en pausa','game.resume':'Toca para continuar','game.newGame':'Nueva partida','game.progress':'Progreso','game.progressText':'{count} de 81 celdas','mode.classic':'Clásico','mode.daily':'Diario','tools.undo':'Deshacer','tools.erase':'Borrar','tools.notes':'Notas','tools.smartNotes':'Notas inteligentes','tools.hint':'Pista','tools.on':'Sí','tools.off':'No','difficulty.easy':'Fácil','difficulty.medium':'Medio','difficulty.hard':'Difícil','difficulty.expert':'Experto','daily.practice':'Práctica diaria','daily.headline':'Encuentra tu<br><em>ritmo.</em>','daily.today':'Reto de hoy','daily.complete':'Reto completado','daily.play':'Jugar ahora','daily.replay':'Repetir','daily.streak':'Racha de {count} día','daily.streakPlural':'Racha de {count} días','hint.title':'Fila {row}, columna {column}: {value}','hint.text':'La celda dorada está revelada. Revisa su fila, columna y bloque 3×3.','footer.focus':'Hecho para momentos de concentración.','footer.offline':'Listo sin conexión','result.time':'Tiempo','result.score':'Puntos de enfoque','result.unlocked':'Logro desbloqueado','result.playAnother':'Jugar otra','result.share':'Compartir resultado','result.complete':'Puzzle completado','result.dailyComplete':'Reto diario completado','result.flawless':'Concentración perfecta.','result.beautiful':'Excelente.','result.gameOver':'Fin del juego','result.almost':'Casi lo tienes.','stats.practice':'Tu práctica','stats.title':'Estadísticas','stats.played':'Jugadas','stats.winRate':'Victorias','stats.streak':'Racha','stats.best':'Mejor tiempo','stats.points':'Puntos','stats.daily':'Retos diarios','stats.achievements':'Logros','stats.keepPlaying':'Seguir jugando','common.notNow':'Ahora no','common.done':'Listo','toast.languageSaved':'Idioma guardado permanentemente',
};

const de = {
  ...en,
  'languageLaunch.eyebrow':'Willkommen · Sveiki · Welcome','languageLaunch.title':'Wähle deine Sprache','languageLaunch.lead':'Wähle die Sprache, die Sudodoku auf diesem Gerät speichern soll.','languageLaunch.selected':'Ausgewählt: {language}','languageLaunch.continue':'Weiter','languageLaunch.changeAnytime':'Du kannst sie jederzeit in den Einstellungen ändern.',
  'mainMenu.personal':'Dein Sudoku-Raum','mainMenu.welcome':'Schön, dass du wieder da bist.<br><em>Finde deinen Flow.</em>',
  'intro.eyebrow':'Ein ruhigeres Rätsel','intro.title':'Denke klar.<br><em>Spiele stilvoll.</em>','intro.lead':'Ein erstklassiges Sudoku-Erlebnis mit hilfreichen Hinweisen, täglichen Aufgaben und lokalem Fortschritt.','intro.featureOffline':'Wirklich offline','intro.featureOfflineText':'Spiele nach dem ersten Besuch überall.','intro.featureCoach':'Sanfte Hilfe','intro.featureCoachText':'Sichtbare Hinweise zeigen den nächsten Schritt.','intro.featureProgress':'Dein Fortschritt','intro.featureProgressText':'Baue Serien auf und schalte Erfolge frei.','intro.start':'Erstes Rätsel beginnen','intro.note':'Sprache und Einstellungen bleiben auf diesem Gerät gespeichert.','settings.personalize':'Mach es zu deinem','settings.title':'Einstellungen','settings.language':'Sprache','settings.languageHelp':'Dauerhaft auf diesem Gerät gespeichert','settings.haptics':'Haptisches Feedback','settings.autoPause':'Automatisch pausieren','settings.replayIntro':'Einführung wiederholen','game.currentPuzzle':'Aktuelles Rätsel','game.mistakes':'Fehler','game.paused':'Spiel pausiert','game.resume':'Tippen zum Fortsetzen','game.newGame':'Neues Spiel','game.progress':'Fortschritt','game.progressText':'{count} von 81 Feldern','mode.classic':'Klassisch','mode.daily':'Täglich','tools.undo':'Zurück','tools.erase':'Löschen','tools.notes':'Notizen','tools.smartNotes':'Smarte Notizen','tools.hint':'Hinweis','tools.on':'An','tools.off':'Aus','difficulty.easy':'Leicht','difficulty.medium':'Mittel','difficulty.hard':'Schwer','difficulty.expert':'Experte','daily.practice':'Tägliche Übung','daily.headline':'Finde deinen<br><em>Flow.</em>','daily.today':'Heutige Aufgabe','daily.complete':'Tagesaufgabe geschafft','daily.play':'Jetzt spielen','daily.replay':'Nochmal','daily.streak':'{count} Tag Serie','daily.streakPlural':'{count} Tage Serie','hint.title':'Zeile {row}, Spalte {column} ist {value}','hint.text':'Das goldene Feld ist aufgedeckt. Prüfe Zeile, Spalte und 3×3-Block.','footer.focus':'Für Momente voller Fokus.','footer.offline':'Offline bereit','result.time':'Zeit','result.score':'Fokuspunkte','result.unlocked':'Erfolg freigeschaltet','result.playAnother':'Noch einmal','result.share':'Ergebnis teilen','result.complete':'Rätsel gelöst','result.dailyComplete':'Tagesaufgabe gelöst','result.flawless':'Makelloser Fokus.','result.beautiful':'Wundervoll gelöst.','result.gameOver':'Spiel vorbei','result.almost':'Fast geschafft.','stats.practice':'Deine Übung','stats.title':'Statistik','stats.played':'Gespielt','stats.winRate':'Siegquote','stats.streak':'Serie','stats.best':'Bestzeit','stats.points':'Fokuspunkte','stats.daily':'Tagessiege','stats.achievements':'Erfolge','stats.keepPlaying':'Weiterspielen','common.notNow':'Nicht jetzt','common.done':'Fertig','toast.languageSaved':'Sprache dauerhaft gespeichert',
};

const uk = {
  ...en,
  'languageLaunch.eyebrow':'Ласкаво просимо · Sveiki · Welcome','languageLaunch.title':'Оберіть свою мову','languageLaunch.lead':'Оберіть мову, яку Sudodoku запам’ятає на цьому пристрої.','languageLaunch.selected':'Обрано: {language}','languageLaunch.continue':'Продовжити','languageLaunch.changeAnytime':'Мову можна будь-коли змінити в Налаштуваннях.',
  'mainMenu.personal':'Ваш простір Sudoku','mainMenu.welcome':'Раді знову вас бачити.<br><em>Знайдіть свій ритм.</em>',
  'intro.eyebrow':'Спокійніша головоломка','intro.title':'Думай ясно.<br><em>Грай красиво.</em>','intro.lead':'Преміальний Sudoku з продуманими підказками, щоденними викликами та прогресом на вашому пристрої.','intro.featureOffline':'Повністю офлайн','intro.featureOfflineText':'Грайте будь-де після першого візиту.','intro.featureCoach':'Делікатні підказки','intro.featureCoachText':'Помітні підказки допомагають знайти наступний крок.','intro.featureProgress':'Особистий прогрес','intro.featureProgressText':'Будуйте серії та відкривайте досягнення.','intro.start':'Почати першу головоломку','intro.note':'Мова й налаштування постійно зберігаються на цьому пристрої.','settings.personalize':'Налаштуйте під себе','settings.title':'Налаштування','settings.language':'Мова','settings.languageHelp':'Постійно зберігається на цьому пристрої','settings.haptics':'Вібровідгук','settings.autoPause':'Автоматична пауза','settings.replayIntro':'Повторити знайомство','game.currentPuzzle':'Поточна головоломка','game.mistakes':'Помилки','game.paused':'Гру призупинено','game.resume':'Торкніться, щоб продовжити','game.newGame':'Нова гра','game.progress':'Прогрес','game.progressText':'{count} з 81 клітинки','mode.classic':'Класика','mode.daily':'Щоденна','tools.undo':'Скасувати','tools.erase':'Стерти','tools.notes':'Нотатки','tools.smartNotes':'Розумні нотатки','tools.hint':'Підказка','tools.on':'Увім.','tools.off':'Вимк.','difficulty.easy':'Легко','difficulty.medium':'Середньо','difficulty.hard':'Складно','difficulty.expert':'Експерт','daily.practice':'Щоденна практика','daily.headline':'Знайди свій<br><em>ритм.</em>','daily.today':'Виклик дня','daily.complete':'Виклик виконано','daily.play':'Грати','daily.replay':'Повторити','daily.streak':'Серія: {count} день','daily.streakPlural':'Серія: {count} днів','hint.title':'Рядок {row}, стовпець {column}: {value}','hint.text':'Золоту клітинку відкрито. Перегляньте її рядок, стовпець і блок 3×3.','footer.focus':'Створено для моментів зосередженості.','footer.offline':'Працює офлайн','result.time':'Час','result.score':'Бали фокусу','result.unlocked':'Досягнення відкрито','result.playAnother':'Грати ще','result.share':'Поділитися','result.complete':'Головоломку завершено','result.dailyComplete':'Щоденний виклик виконано','result.flawless':'Бездоганний фокус.','result.beautiful':'Чудова робота.','result.gameOver':'Гру завершено','result.almost':'Майже вдалося.','stats.practice':'Ваша практика','stats.title':'Статистика','stats.played':'Зіграно','stats.winRate':'Перемоги','stats.streak':'Серія','stats.best':'Кращий час','stats.points':'Бали фокусу','stats.daily':'Щоденні перемоги','stats.achievements':'Досягнення','stats.keepPlaying':'Продовжити','common.notNow':'Не зараз','common.done':'Готово','toast.languageSaved':'Мову збережено назавжди',
};

const dictionaries = { en, lt, es, de, uk };

export function translate(locale, key, variables = {}) {
  const template = dictionaries[locale]?.[key] ?? en[key] ?? key;
  return String(template).replace(/\{(\w+)\}/g, (_, name) => variables[name] ?? `{${name}}`);
}

export function applyDocumentTranslations(locale) {
  document.documentElement.lang = locale;
  document.querySelectorAll('[data-i18n]').forEach((element) => { element.textContent = translate(locale, element.dataset.i18n); });
  document.querySelectorAll('[data-i18n-html]').forEach((element) => { element.innerHTML = translate(locale, element.dataset.i18nHtml); });
}
